// Code generated by MockGen. DO NOT EDIT.
// Source: authentication.go
//
// Generated by this command:
//
//	mockgen -source=authentication.go -destination=tests/authentication_mock.go -package tests -typed
//

// Package tests is a generated GoMock package.
package tests

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthentication is a mock of Authentication interface.
type MockAuthentication struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationMockRecorder
	isgomock struct{}
}

// MockAuthenticationMockRecorder is the mock recorder for MockAuthentication.
type MockAuthenticationMockRecorder struct {
	mock *MockAuthentication
}

// NewMockAuthentication creates a new mock instance.
func NewMockAuthentication(ctrl *gomock.Controller) *MockAuthentication {
	mock := &MockAuthentication{ctrl: ctrl}
	mock.recorder = &MockAuthenticationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthentication) EXPECT() *MockAuthenticationMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockAuthentication) GetAccessToken() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockAuthenticationMockRecorder) GetAccessToken() *MockAuthenticationGetAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockAuthentication)(nil).GetAccessToken))
	return &MockAuthenticationGetAccessTokenCall{Call: call}
}

// MockAuthenticationGetAccessTokenCall wrap *gomock.Call
type MockAuthenticationGetAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticationGetAccessTokenCall) Return(arg0 string, arg1 error) *MockAuthenticationGetAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticationGetAccessTokenCall) Do(f func() (string, error)) *MockAuthenticationGetAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticationGetAccessTokenCall) DoAndReturn(f func() (string, error)) *MockAuthenticationGetAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsExpired mocks base method.
func (m *MockAuthentication) IsExpired() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExpired")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExpired indicates an expected call of IsExpired.
func (mr *MockAuthenticationMockRecorder) IsExpired() *MockAuthenticationIsExpiredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExpired", reflect.TypeOf((*MockAuthentication)(nil).IsExpired))
	return &MockAuthenticationIsExpiredCall{Call: call}
}

// MockAuthenticationIsExpiredCall wrap *gomock.Call
type MockAuthenticationIsExpiredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthenticationIsExpiredCall) Return(arg0 bool) *MockAuthenticationIsExpiredCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthenticationIsExpiredCall) Do(f func() bool) *MockAuthenticationIsExpiredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthenticationIsExpiredCall) DoAndReturn(f func() bool) *MockAuthenticationIsExpiredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
