/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeploymentContainer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentContainer{}

// DeploymentContainer struct for DeploymentContainer
type DeploymentContainer struct {
	// This deployment container's ID
	Id string `json:"id"`
	// If set to 1, all application instances will be gracefully removed inside the container. Afterwards this container will be set to inactive
	MarkedForDeletion  int32                         `json:"markedForDeletion"`
	ContainerLocations []DeploymentContainerLocation `json:"containerLocations"`
}

type _DeploymentContainer DeploymentContainer

// NewDeploymentContainer instantiates a new DeploymentContainer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentContainer(id string, markedForDeletion int32, containerLocations []DeploymentContainerLocation) *DeploymentContainer {
	this := DeploymentContainer{}
	this.Id = id
	this.MarkedForDeletion = markedForDeletion
	this.ContainerLocations = containerLocations
	return &this
}

// NewDeploymentContainerWithDefaults instantiates a new DeploymentContainer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentContainerWithDefaults() *DeploymentContainer {
	this := DeploymentContainer{}
	return &this
}

// GetId returns the Id field value
func (o *DeploymentContainer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeploymentContainer) SetId(v string) {
	o.Id = v
}

// GetMarkedForDeletion returns the MarkedForDeletion field value
func (o *DeploymentContainer) GetMarkedForDeletion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MarkedForDeletion
}

// GetMarkedForDeletionOk returns a tuple with the MarkedForDeletion field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainer) GetMarkedForDeletionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarkedForDeletion, true
}

// SetMarkedForDeletion sets field value
func (o *DeploymentContainer) SetMarkedForDeletion(v int32) {
	o.MarkedForDeletion = v
}

// GetContainerLocations returns the ContainerLocations field value
func (o *DeploymentContainer) GetContainerLocations() []DeploymentContainerLocation {
	if o == nil {
		var ret []DeploymentContainerLocation
		return ret
	}

	return o.ContainerLocations
}

// GetContainerLocationsOk returns a tuple with the ContainerLocations field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainer) GetContainerLocationsOk() ([]DeploymentContainerLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContainerLocations, true
}

// SetContainerLocations sets field value
func (o *DeploymentContainer) SetContainerLocations(v []DeploymentContainerLocation) {
	o.ContainerLocations = v
}

func (o DeploymentContainer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentContainer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["markedForDeletion"] = o.MarkedForDeletion
	toSerialize["containerLocations"] = o.ContainerLocations
	return toSerialize, nil
}

func (o *DeploymentContainer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"markedForDeletion",
		"containerLocations",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentContainer := _DeploymentContainer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentContainer)

	if err != nil {
		return err
	}

	*o = DeploymentContainer(varDeploymentContainer)

	return err
}

type NullableDeploymentContainer struct {
	value *DeploymentContainer
	isSet bool
}

func (v NullableDeploymentContainer) Get() *DeploymentContainer {
	return v.value
}

func (v *NullableDeploymentContainer) Set(val *DeploymentContainer) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentContainer(val *DeploymentContainer) *NullableDeploymentContainer {
	return &NullableDeploymentContainer{value: val, isSet: true}
}

func (v NullableDeploymentContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
