/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceCpuDataTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceCpuDataTelemetry{}

// ApplicationInstanceCpuDataTelemetry struct for ApplicationInstanceCpuDataTelemetry
type ApplicationInstanceCpuDataTelemetry struct {
	// The time at which the last update occurred
	Timestamp int32 `json:"timestamp"`
	// Percentage of cpu used across all cores
	Cpu int32 `json:"cpu"`
}

type _ApplicationInstanceCpuDataTelemetry ApplicationInstanceCpuDataTelemetry

// NewApplicationInstanceCpuDataTelemetry instantiates a new ApplicationInstanceCpuDataTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceCpuDataTelemetry(timestamp int32, cpu int32) *ApplicationInstanceCpuDataTelemetry {
	this := ApplicationInstanceCpuDataTelemetry{}
	this.Timestamp = timestamp
	this.Cpu = cpu
	return &this
}

// NewApplicationInstanceCpuDataTelemetryWithDefaults instantiates a new ApplicationInstanceCpuDataTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceCpuDataTelemetryWithDefaults() *ApplicationInstanceCpuDataTelemetry {
	this := ApplicationInstanceCpuDataTelemetry{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *ApplicationInstanceCpuDataTelemetry) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceCpuDataTelemetry) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *ApplicationInstanceCpuDataTelemetry) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetCpu returns the Cpu field value
func (o *ApplicationInstanceCpuDataTelemetry) GetCpu() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceCpuDataTelemetry) GetCpuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *ApplicationInstanceCpuDataTelemetry) SetCpu(v int32) {
	o.Cpu = v
}

func (o ApplicationInstanceCpuDataTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceCpuDataTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["cpu"] = o.Cpu
	return toSerialize, nil
}

func (o *ApplicationInstanceCpuDataTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"cpu",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceCpuDataTelemetry := _ApplicationInstanceCpuDataTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceCpuDataTelemetry)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceCpuDataTelemetry(varApplicationInstanceCpuDataTelemetry)

	return err
}

type NullableApplicationInstanceCpuDataTelemetry struct {
	value *ApplicationInstanceCpuDataTelemetry
	isSet bool
}

func (v NullableApplicationInstanceCpuDataTelemetry) Get() *ApplicationInstanceCpuDataTelemetry {
	return v.value
}

func (v *NullableApplicationInstanceCpuDataTelemetry) Set(val *ApplicationInstanceCpuDataTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceCpuDataTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceCpuDataTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceCpuDataTelemetry(val *ApplicationInstanceCpuDataTelemetry) *NullableApplicationInstanceCpuDataTelemetry {
	return &NullableApplicationInstanceCpuDataTelemetry{value: val, isSet: true}
}

func (v NullableApplicationInstanceCpuDataTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceCpuDataTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
