/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostNetworkDataTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostNetworkDataTelemetry{}

// HostNetworkDataTelemetry struct for HostNetworkDataTelemetry
type HostNetworkDataTelemetry struct {
	// The time at which the last update occurred
	Timestamp int32 `json:"timestamp"`
	// The network's ingress in bytes
	NetworkIngress int32 `json:"networkIngress"`
	// The network's egress in bytes
	NetworkEgress int32 `json:"networkEgress"`
}

type _HostNetworkDataTelemetry HostNetworkDataTelemetry

// NewHostNetworkDataTelemetry instantiates a new HostNetworkDataTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostNetworkDataTelemetry(timestamp int32, networkIngress int32, networkEgress int32) *HostNetworkDataTelemetry {
	this := HostNetworkDataTelemetry{}
	this.Timestamp = timestamp
	this.NetworkIngress = networkIngress
	this.NetworkEgress = networkEgress
	return &this
}

// NewHostNetworkDataTelemetryWithDefaults instantiates a new HostNetworkDataTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostNetworkDataTelemetryWithDefaults() *HostNetworkDataTelemetry {
	this := HostNetworkDataTelemetry{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *HostNetworkDataTelemetry) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HostNetworkDataTelemetry) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HostNetworkDataTelemetry) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetNetworkIngress returns the NetworkIngress field value
func (o *HostNetworkDataTelemetry) GetNetworkIngress() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkIngress
}

// GetNetworkIngressOk returns a tuple with the NetworkIngress field value
// and a boolean to check if the value has been set.
func (o *HostNetworkDataTelemetry) GetNetworkIngressOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkIngress, true
}

// SetNetworkIngress sets field value
func (o *HostNetworkDataTelemetry) SetNetworkIngress(v int32) {
	o.NetworkIngress = v
}

// GetNetworkEgress returns the NetworkEgress field value
func (o *HostNetworkDataTelemetry) GetNetworkEgress() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkEgress
}

// GetNetworkEgressOk returns a tuple with the NetworkEgress field value
// and a boolean to check if the value has been set.
func (o *HostNetworkDataTelemetry) GetNetworkEgressOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkEgress, true
}

// SetNetworkEgress sets field value
func (o *HostNetworkDataTelemetry) SetNetworkEgress(v int32) {
	o.NetworkEgress = v
}

func (o HostNetworkDataTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostNetworkDataTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["networkIngress"] = o.NetworkIngress
	toSerialize["networkEgress"] = o.NetworkEgress
	return toSerialize, nil
}

func (o *HostNetworkDataTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"networkIngress",
		"networkEgress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostNetworkDataTelemetry := _HostNetworkDataTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostNetworkDataTelemetry)

	if err != nil {
		return err
	}

	*o = HostNetworkDataTelemetry(varHostNetworkDataTelemetry)

	return err
}

type NullableHostNetworkDataTelemetry struct {
	value *HostNetworkDataTelemetry
	isSet bool
}

func (v NullableHostNetworkDataTelemetry) Get() *HostNetworkDataTelemetry {
	return v.value
}

func (v *NullableHostNetworkDataTelemetry) Set(val *HostNetworkDataTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableHostNetworkDataTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableHostNetworkDataTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostNetworkDataTelemetry(val *HostNetworkDataTelemetry) *NullableHostNetworkDataTelemetry {
	return &NullableHostNetworkDataTelemetry{value: val, isSet: true}
}

func (v NullableHostNetworkDataTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostNetworkDataTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
