/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostOnlineStatusHistoryHostTypeTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostOnlineStatusHistoryHostTypeTelemetry{}

// HostOnlineStatusHistoryHostTypeTelemetry struct for HostOnlineStatusHistoryHostTypeTelemetry
type HostOnlineStatusHistoryHostTypeTelemetry struct {
	// The time at which the last update occurred
	Timestamp int32 `json:"timestamp"`
	// Contains the data object
	Data []HostOnlineStatusHistoryDataTelemetry `json:"data"`
}

type _HostOnlineStatusHistoryHostTypeTelemetry HostOnlineStatusHistoryHostTypeTelemetry

// NewHostOnlineStatusHistoryHostTypeTelemetry instantiates a new HostOnlineStatusHistoryHostTypeTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostOnlineStatusHistoryHostTypeTelemetry(timestamp int32, data []HostOnlineStatusHistoryDataTelemetry) *HostOnlineStatusHistoryHostTypeTelemetry {
	this := HostOnlineStatusHistoryHostTypeTelemetry{}
	this.Timestamp = timestamp
	this.Data = data
	return &this
}

// NewHostOnlineStatusHistoryHostTypeTelemetryWithDefaults instantiates a new HostOnlineStatusHistoryHostTypeTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostOnlineStatusHistoryHostTypeTelemetryWithDefaults() *HostOnlineStatusHistoryHostTypeTelemetry {
	this := HostOnlineStatusHistoryHostTypeTelemetry{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *HostOnlineStatusHistoryHostTypeTelemetry) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HostOnlineStatusHistoryHostTypeTelemetry) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HostOnlineStatusHistoryHostTypeTelemetry) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetData returns the Data field value
func (o *HostOnlineStatusHistoryHostTypeTelemetry) GetData() []HostOnlineStatusHistoryDataTelemetry {
	if o == nil {
		var ret []HostOnlineStatusHistoryDataTelemetry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *HostOnlineStatusHistoryHostTypeTelemetry) GetDataOk() ([]HostOnlineStatusHistoryDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *HostOnlineStatusHistoryHostTypeTelemetry) SetData(v []HostOnlineStatusHistoryDataTelemetry) {
	o.Data = v
}

func (o HostOnlineStatusHistoryHostTypeTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostOnlineStatusHistoryHostTypeTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *HostOnlineStatusHistoryHostTypeTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostOnlineStatusHistoryHostTypeTelemetry := _HostOnlineStatusHistoryHostTypeTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostOnlineStatusHistoryHostTypeTelemetry)

	if err != nil {
		return err
	}

	*o = HostOnlineStatusHistoryHostTypeTelemetry(varHostOnlineStatusHistoryHostTypeTelemetry)

	return err
}

type NullableHostOnlineStatusHistoryHostTypeTelemetry struct {
	value *HostOnlineStatusHistoryHostTypeTelemetry
	isSet bool
}

func (v NullableHostOnlineStatusHistoryHostTypeTelemetry) Get() *HostOnlineStatusHistoryHostTypeTelemetry {
	return v.value
}

func (v *NullableHostOnlineStatusHistoryHostTypeTelemetry) Set(val *HostOnlineStatusHistoryHostTypeTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableHostOnlineStatusHistoryHostTypeTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableHostOnlineStatusHistoryHostTypeTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostOnlineStatusHistoryHostTypeTelemetry(val *HostOnlineStatusHistoryHostTypeTelemetry) *NullableHostOnlineStatusHistoryHostTypeTelemetry {
	return &NullableHostOnlineStatusHistoryHostTypeTelemetry{value: val, isSet: true}
}

func (v NullableHostOnlineStatusHistoryHostTypeTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostOnlineStatusHistoryHostTypeTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
