/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Host type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Host{}

// Host struct for Host
type Host struct {
	// The ID of this host
	Id int32 `json:"id"`
	// The ID of the user who owns this server
	UserId int32 `json:"userId"`
	// The ID of the physical machine
	ServerId int32 `json:"serverId"`
	// The name of the physical machine
	ServerName string `json:"serverName"`
	// The type of the server: * 1: Bare metal server * 2: Flex metal server * 3: Virtual machine
	ServerType int32 `json:"serverType"`
	// The name of the project for the host
	ProjectName *string `json:"projectName,omitempty"`
	// The name of the server defined by client
	ClientServerName *string `json:"clientServerName,omitempty"`
	// Client statement for the host
	ClientState *string `json:"clientState,omitempty"`
	// The host name
	LiveHostName string `json:"liveHostName"`
	// 0 if this is a bare metal server, 1 if it's a VM. Use `serverType` instead
	// Deprecated
	IsVirtual int32 `json:"isVirtual"`
	// Host category. Normally \"Dedicated Game Servers\" or \"Dedicated Servers\", but can be \"Broken\" if the server is in a degraded state
	Category string `json:"category"`
	// Operating system ID, must be one of [`GET /v3/operatingsystem`](all#/OperatingSystem/getOperatingsystems)
	OsId int32 `json:"osId"`
	// Legacy location ID (not used for ODP)
	LocationId int32 `json:"locationId"`
	// Datacenter location ID. Points to one of [`GET /v3/cloud/dcLocation`](#/Cloud/getCloudDcLocations)
	DcLocationId int32 `json:"dcLocationId"`
	// The instance type of this server, which is one of [`GET /v3/host/instanceType`](#/Host/getHostInstanceTypes) for a bare metal, or one of [`GET /v3/cloud/instanceType`](#/Cloud/getCloudInstanceTypes) for a virtual machine
	InstanceType string `json:"instanceType"`
	// The fleet ID, if this host has been assigned to a fleet If `0`, the host has not been assigned to a fleet, otherwise, the fleet is assigned to this host and the host can serve application instances for that fleet.
	FleetId string `json:"fleetId"`
	// The ID of a new fleet that is to be assigned to this host after performing a bulkReserve operation at [`POST /v3/fleet/host/bulkReserve`](#/Fleet/createFleetHostBulkReserve)
	NewFleetId NullableString `json:"newFleetId"`
	// Unix timestamp when fleet assigned to the host
	FleetAssociatedSince int32 `json:"fleetAssociatedSince"`
	// The name of the rack the host is located
	RackName string `json:"rackName"`
	// The date at which this host became active
	DateStart string `json:"dateStart"`
	// The date at which this host will expire
	DateEnd string `json:"dateEnd"`
	// The date at which this host was cancelled
	DateCancelled string `json:"dateCancelled"`
	// The date at which the contract ends (if applicable)
	DateEndContract string `json:"dateEndContract"`
	// The contract period in months
	ContractPeriod int32 `json:"contractPeriod"`
	// The service extend period in months
	ExtendPeriod int32 `json:"extendPeriod"`
	// The cancellation period in months
	CancellationPeriod int32 `json:"cancellationPeriod"`
	// Purchase order, if one has been supplied via our billing department
	PurchaseOrder string `json:"purchaseOrder"`
	// The payment term in days (how many days are invoices generated before dateEnd)
	PaymentTerm int32 `json:"paymentTerm"`
	// The price of this host per month in cents (see `currencyId` for currency)
	PricePerMonth string `json:"pricePerMonth"`
	// The price of traffic overuse in cents (per TB) (see `currencyId` for currency)
	PricePerTbOveruse string `json:"pricePerTbOveruse"`
	// The currency of the `pricePerMonth` field: * 0: EURO * 1: USD * 9: YEN
	CurrencyId int32 `json:"currencyId"`
	// The bandwidth billing method for this service: * 1: unmetered connection * 2: measured in TB per month * 3: measured in mbit 95th percentile
	BandwidthBillingType int32 `json:"bandwidthBillingType"`
	// The contractual maximum bandwidth usage value. In GB if bandwidthBillingType equals `2`, in mbit otherwise
	BandwidthContractual int32 `json:"bandwidthContractual"`
	// All IP addresses assigned to this host
	IpAddress []HostIP `json:"ipAddress"`
	// The server manufacturer brand name
	Brand string `json:"brand"`
	// The model of the server
	Model string `json:"model"`
	// Number of CPUs in this host
	NumCpu  int32  `json:"numCpu"`
	CpuInfo string `json:"cpuInfo"`
	CpuType string `json:"cpuType"`
	// Percentage of cpu used across all cores
	CpuLoad float32 `json:"cpuLoad"`
	Cpu     HostCpu `json:"cpu"`
	// The amount of memory that is used by the host (in megabytes)
	MemUsed int32 `json:"memUsed"`
	// The amount of memory that is available on the host (in megabytes)
	MemMax int32 `json:"memMax"`
	// The amount of free memory that is available on the host (in megabytes)
	MemFree int32        `json:"memFree"`
	Disk    []HostDisk   `json:"disk"`
	Memory  []HostMemory `json:"memory"`
	// If the host is reserved for a fleet isReserve set to 1
	IsReserve int32 `json:"isReserve"`
	// Custom key/value pairs that can be used for host
	Labels []Label `json:"filters,omitempty"`
	// The service tag of the host
	ServiceTag string `json:"serviceTag"`
	// If the host is available for game hosting platform isODP set to 1
	IsODP int32 `json:"isODP"`
	// ID of Flex Metal order if this is a flex metal server
	FmOrderId NullableString `json:"fmOrderId"`
	// Status of server auto install if it was started by one. (created / installing / finished / failed)
	InstallStatus NullableString `json:"installStatus"`
	// Whether the host is running or not
	Status string `json:"status"`
	// The uptime of the host. Read-only. Only provided if the server checked-in recently
	Uptime *int32 `json:"uptime,omitempty"`
	// Monthly traffic of all incoming and outgoing bandwidth in GB or Mbit depending on host configuration
	TrafficSum int32 `json:"trafficSum"`
	// A list of uplinks attached to this host
	Uplinks []HostUplink `json:"uplinks"`
	// Whether the host has free incoming traffic or not
	FreeIncomingTraffic bool `json:"freeIncomingTraffic"`
	// The outgoing traffic (Mbit or GB)
	OutgoingTrafficSum int32 `json:"outgoingTrafficSum"`
	// The incoming traffic (Mbit or GB)
	IncomingTrafficSum int32 `json:"incomingTrafficSum"`
}

type _Host Host

// NewHost instantiates a new Host object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHost(id int32, userId int32, serverId int32, serverName string, serverType int32, liveHostName string, isVirtual int32, category string, osId int32, locationId int32, dcLocationId int32, instanceType string, fleetId string, newFleetId NullableString, fleetAssociatedSince int32, rackName string, dateStart string, dateEnd string, dateCancelled string, dateEndContract string, contractPeriod int32, extendPeriod int32, cancellationPeriod int32, purchaseOrder string, paymentTerm int32, pricePerMonth string, pricePerTbOveruse string, currencyId int32, bandwidthBillingType int32, bandwidthContractual int32, ipAddress []HostIP, brand string, model string, numCpu int32, cpuInfo string, cpuType string, cpuLoad float32, cpu HostCpu, memUsed int32, memMax int32, memFree int32, disk []HostDisk, memory []HostMemory, isReserve int32, serviceTag string, isODP int32, fmOrderId NullableString, installStatus NullableString, status string, trafficSum int32, uplinks []HostUplink, freeIncomingTraffic bool, outgoingTrafficSum int32, incomingTrafficSum int32) *Host {
	this := Host{}
	this.Id = id
	this.UserId = userId
	this.ServerId = serverId
	this.ServerName = serverName
	this.ServerType = serverType
	this.LiveHostName = liveHostName
	this.IsVirtual = isVirtual
	this.Category = category
	this.OsId = osId
	this.LocationId = locationId
	this.DcLocationId = dcLocationId
	this.InstanceType = instanceType
	this.FleetId = fleetId
	this.NewFleetId = newFleetId
	this.FleetAssociatedSince = fleetAssociatedSince
	this.RackName = rackName
	this.DateStart = dateStart
	this.DateEnd = dateEnd
	this.DateCancelled = dateCancelled
	this.DateEndContract = dateEndContract
	this.ContractPeriod = contractPeriod
	this.ExtendPeriod = extendPeriod
	this.CancellationPeriod = cancellationPeriod
	this.PurchaseOrder = purchaseOrder
	this.PaymentTerm = paymentTerm
	this.PricePerMonth = pricePerMonth
	this.PricePerTbOveruse = pricePerTbOveruse
	this.CurrencyId = currencyId
	this.BandwidthBillingType = bandwidthBillingType
	this.BandwidthContractual = bandwidthContractual
	this.IpAddress = ipAddress
	this.Brand = brand
	this.Model = model
	this.NumCpu = numCpu
	this.CpuInfo = cpuInfo
	this.CpuType = cpuType
	this.CpuLoad = cpuLoad
	this.Cpu = cpu
	this.MemUsed = memUsed
	this.MemMax = memMax
	this.MemFree = memFree
	this.Disk = disk
	this.Memory = memory
	this.IsReserve = isReserve
	this.ServiceTag = serviceTag
	this.IsODP = isODP
	this.FmOrderId = fmOrderId
	this.InstallStatus = installStatus
	this.Status = status
	this.TrafficSum = trafficSum
	this.Uplinks = uplinks
	this.FreeIncomingTraffic = freeIncomingTraffic
	this.OutgoingTrafficSum = outgoingTrafficSum
	this.IncomingTrafficSum = incomingTrafficSum
	return &this
}

// NewHostWithDefaults instantiates a new Host object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostWithDefaults() *Host {
	this := Host{}
	return &this
}

// GetId returns the Id field value
func (o *Host) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Host) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Host) SetId(v int32) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *Host) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Host) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Host) SetUserId(v int32) {
	o.UserId = v
}

// GetServerId returns the ServerId field value
func (o *Host) GetServerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value
// and a boolean to check if the value has been set.
func (o *Host) GetServerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerId, true
}

// SetServerId sets field value
func (o *Host) SetServerId(v int32) {
	o.ServerId = v
}

// GetServerName returns the ServerName field value
func (o *Host) GetServerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value
// and a boolean to check if the value has been set.
func (o *Host) GetServerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerName, true
}

// SetServerName sets field value
func (o *Host) SetServerName(v string) {
	o.ServerName = v
}

// GetServerType returns the ServerType field value
func (o *Host) GetServerType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerType
}

// GetServerTypeOk returns a tuple with the ServerType field value
// and a boolean to check if the value has been set.
func (o *Host) GetServerTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerType, true
}

// SetServerType sets field value
func (o *Host) SetServerType(v int32) {
	o.ServerType = v
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *Host) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *Host) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *Host) SetProjectName(v string) {
	o.ProjectName = &v
}

// GetClientServerName returns the ClientServerName field value if set, zero value otherwise.
func (o *Host) GetClientServerName() string {
	if o == nil || IsNil(o.ClientServerName) {
		var ret string
		return ret
	}
	return *o.ClientServerName
}

// GetClientServerNameOk returns a tuple with the ClientServerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetClientServerNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClientServerName) {
		return nil, false
	}
	return o.ClientServerName, true
}

// HasClientServerName returns a boolean if a field has been set.
func (o *Host) HasClientServerName() bool {
	if o != nil && !IsNil(o.ClientServerName) {
		return true
	}

	return false
}

// SetClientServerName gets a reference to the given string and assigns it to the ClientServerName field.
func (o *Host) SetClientServerName(v string) {
	o.ClientServerName = &v
}

// GetClientState returns the ClientState field value if set, zero value otherwise.
func (o *Host) GetClientState() string {
	if o == nil || IsNil(o.ClientState) {
		var ret string
		return ret
	}
	return *o.ClientState
}

// GetClientStateOk returns a tuple with the ClientState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetClientStateOk() (*string, bool) {
	if o == nil || IsNil(o.ClientState) {
		return nil, false
	}
	return o.ClientState, true
}

// HasClientState returns a boolean if a field has been set.
func (o *Host) HasClientState() bool {
	if o != nil && !IsNil(o.ClientState) {
		return true
	}

	return false
}

// SetClientState gets a reference to the given string and assigns it to the ClientState field.
func (o *Host) SetClientState(v string) {
	o.ClientState = &v
}

// GetLiveHostName returns the LiveHostName field value
func (o *Host) GetLiveHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LiveHostName
}

// GetLiveHostNameOk returns a tuple with the LiveHostName field value
// and a boolean to check if the value has been set.
func (o *Host) GetLiveHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LiveHostName, true
}

// SetLiveHostName sets field value
func (o *Host) SetLiveHostName(v string) {
	o.LiveHostName = v
}

// GetIsVirtual returns the IsVirtual field value
// Deprecated
func (o *Host) GetIsVirtual() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IsVirtual
}

// GetIsVirtualOk returns a tuple with the IsVirtual field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *Host) GetIsVirtualOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsVirtual, true
}

// SetIsVirtual sets field value
// Deprecated
func (o *Host) SetIsVirtual(v int32) {
	o.IsVirtual = v
}

// GetCategory returns the Category field value
func (o *Host) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *Host) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *Host) SetCategory(v string) {
	o.Category = v
}

// GetOsId returns the OsId field value
func (o *Host) GetOsId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OsId
}

// GetOsIdOk returns a tuple with the OsId field value
// and a boolean to check if the value has been set.
func (o *Host) GetOsIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OsId, true
}

// SetOsId sets field value
func (o *Host) SetOsId(v int32) {
	o.OsId = v
}

// GetLocationId returns the LocationId field value
func (o *Host) GetLocationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *Host) GetLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *Host) SetLocationId(v int32) {
	o.LocationId = v
}

// GetDcLocationId returns the DcLocationId field value
func (o *Host) GetDcLocationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DcLocationId
}

// GetDcLocationIdOk returns a tuple with the DcLocationId field value
// and a boolean to check if the value has been set.
func (o *Host) GetDcLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DcLocationId, true
}

// SetDcLocationId sets field value
func (o *Host) SetDcLocationId(v int32) {
	o.DcLocationId = v
}

// GetInstanceType returns the InstanceType field value
func (o *Host) GetInstanceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value
// and a boolean to check if the value has been set.
func (o *Host) GetInstanceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceType, true
}

// SetInstanceType sets field value
func (o *Host) SetInstanceType(v string) {
	o.InstanceType = v
}

// GetFleetId returns the FleetId field value
func (o *Host) GetFleetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FleetId
}

// GetFleetIdOk returns a tuple with the FleetId field value
// and a boolean to check if the value has been set.
func (o *Host) GetFleetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FleetId, true
}

// SetFleetId sets field value
func (o *Host) SetFleetId(v string) {
	o.FleetId = v
}

// GetNewFleetId returns the NewFleetId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Host) GetNewFleetId() string {
	if o == nil || o.NewFleetId.Get() == nil {
		var ret string
		return ret
	}

	return *o.NewFleetId.Get()
}

// GetNewFleetIdOk returns a tuple with the NewFleetId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Host) GetNewFleetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewFleetId.Get(), o.NewFleetId.IsSet()
}

// SetNewFleetId sets field value
func (o *Host) SetNewFleetId(v string) {
	o.NewFleetId.Set(&v)
}

// GetFleetAssociatedSince returns the FleetAssociatedSince field value
func (o *Host) GetFleetAssociatedSince() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FleetAssociatedSince
}

// GetFleetAssociatedSinceOk returns a tuple with the FleetAssociatedSince field value
// and a boolean to check if the value has been set.
func (o *Host) GetFleetAssociatedSinceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FleetAssociatedSince, true
}

// SetFleetAssociatedSince sets field value
func (o *Host) SetFleetAssociatedSince(v int32) {
	o.FleetAssociatedSince = v
}

// GetRackName returns the RackName field value
func (o *Host) GetRackName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RackName
}

// GetRackNameOk returns a tuple with the RackName field value
// and a boolean to check if the value has been set.
func (o *Host) GetRackNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RackName, true
}

// SetRackName sets field value
func (o *Host) SetRackName(v string) {
	o.RackName = v
}

// GetDateStart returns the DateStart field value
func (o *Host) GetDateStart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateStart
}

// GetDateStartOk returns a tuple with the DateStart field value
// and a boolean to check if the value has been set.
func (o *Host) GetDateStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateStart, true
}

// SetDateStart sets field value
func (o *Host) SetDateStart(v string) {
	o.DateStart = v
}

// GetDateEnd returns the DateEnd field value
func (o *Host) GetDateEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateEnd
}

// GetDateEndOk returns a tuple with the DateEnd field value
// and a boolean to check if the value has been set.
func (o *Host) GetDateEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateEnd, true
}

// SetDateEnd sets field value
func (o *Host) SetDateEnd(v string) {
	o.DateEnd = v
}

// GetDateCancelled returns the DateCancelled field value
func (o *Host) GetDateCancelled() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateCancelled
}

// GetDateCancelledOk returns a tuple with the DateCancelled field value
// and a boolean to check if the value has been set.
func (o *Host) GetDateCancelledOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateCancelled, true
}

// SetDateCancelled sets field value
func (o *Host) SetDateCancelled(v string) {
	o.DateCancelled = v
}

// GetDateEndContract returns the DateEndContract field value
func (o *Host) GetDateEndContract() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DateEndContract
}

// GetDateEndContractOk returns a tuple with the DateEndContract field value
// and a boolean to check if the value has been set.
func (o *Host) GetDateEndContractOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DateEndContract, true
}

// SetDateEndContract sets field value
func (o *Host) SetDateEndContract(v string) {
	o.DateEndContract = v
}

// GetContractPeriod returns the ContractPeriod field value
func (o *Host) GetContractPeriod() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ContractPeriod
}

// GetContractPeriodOk returns a tuple with the ContractPeriod field value
// and a boolean to check if the value has been set.
func (o *Host) GetContractPeriodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractPeriod, true
}

// SetContractPeriod sets field value
func (o *Host) SetContractPeriod(v int32) {
	o.ContractPeriod = v
}

// GetExtendPeriod returns the ExtendPeriod field value
func (o *Host) GetExtendPeriod() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExtendPeriod
}

// GetExtendPeriodOk returns a tuple with the ExtendPeriod field value
// and a boolean to check if the value has been set.
func (o *Host) GetExtendPeriodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExtendPeriod, true
}

// SetExtendPeriod sets field value
func (o *Host) SetExtendPeriod(v int32) {
	o.ExtendPeriod = v
}

// GetCancellationPeriod returns the CancellationPeriod field value
func (o *Host) GetCancellationPeriod() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CancellationPeriod
}

// GetCancellationPeriodOk returns a tuple with the CancellationPeriod field value
// and a boolean to check if the value has been set.
func (o *Host) GetCancellationPeriodOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancellationPeriod, true
}

// SetCancellationPeriod sets field value
func (o *Host) SetCancellationPeriod(v int32) {
	o.CancellationPeriod = v
}

// GetPurchaseOrder returns the PurchaseOrder field value
func (o *Host) GetPurchaseOrder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PurchaseOrder
}

// GetPurchaseOrderOk returns a tuple with the PurchaseOrder field value
// and a boolean to check if the value has been set.
func (o *Host) GetPurchaseOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PurchaseOrder, true
}

// SetPurchaseOrder sets field value
func (o *Host) SetPurchaseOrder(v string) {
	o.PurchaseOrder = v
}

// GetPaymentTerm returns the PaymentTerm field value
func (o *Host) GetPaymentTerm() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PaymentTerm
}

// GetPaymentTermOk returns a tuple with the PaymentTerm field value
// and a boolean to check if the value has been set.
func (o *Host) GetPaymentTermOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentTerm, true
}

// SetPaymentTerm sets field value
func (o *Host) SetPaymentTerm(v int32) {
	o.PaymentTerm = v
}

// GetPricePerMonth returns the PricePerMonth field value
func (o *Host) GetPricePerMonth() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PricePerMonth
}

// GetPricePerMonthOk returns a tuple with the PricePerMonth field value
// and a boolean to check if the value has been set.
func (o *Host) GetPricePerMonthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PricePerMonth, true
}

// SetPricePerMonth sets field value
func (o *Host) SetPricePerMonth(v string) {
	o.PricePerMonth = v
}

// GetPricePerTbOveruse returns the PricePerTbOveruse field value
func (o *Host) GetPricePerTbOveruse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PricePerTbOveruse
}

// GetPricePerTbOveruseOk returns a tuple with the PricePerTbOveruse field value
// and a boolean to check if the value has been set.
func (o *Host) GetPricePerTbOveruseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PricePerTbOveruse, true
}

// SetPricePerTbOveruse sets field value
func (o *Host) SetPricePerTbOveruse(v string) {
	o.PricePerTbOveruse = v
}

// GetCurrencyId returns the CurrencyId field value
func (o *Host) GetCurrencyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CurrencyId
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value
// and a boolean to check if the value has been set.
func (o *Host) GetCurrencyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyId, true
}

// SetCurrencyId sets field value
func (o *Host) SetCurrencyId(v int32) {
	o.CurrencyId = v
}

// GetBandwidthBillingType returns the BandwidthBillingType field value
func (o *Host) GetBandwidthBillingType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BandwidthBillingType
}

// GetBandwidthBillingTypeOk returns a tuple with the BandwidthBillingType field value
// and a boolean to check if the value has been set.
func (o *Host) GetBandwidthBillingTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BandwidthBillingType, true
}

// SetBandwidthBillingType sets field value
func (o *Host) SetBandwidthBillingType(v int32) {
	o.BandwidthBillingType = v
}

// GetBandwidthContractual returns the BandwidthContractual field value
func (o *Host) GetBandwidthContractual() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BandwidthContractual
}

// GetBandwidthContractualOk returns a tuple with the BandwidthContractual field value
// and a boolean to check if the value has been set.
func (o *Host) GetBandwidthContractualOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BandwidthContractual, true
}

// SetBandwidthContractual sets field value
func (o *Host) SetBandwidthContractual(v int32) {
	o.BandwidthContractual = v
}

// GetIpAddress returns the IpAddress field value
func (o *Host) GetIpAddress() []HostIP {
	if o == nil {
		var ret []HostIP
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *Host) GetIpAddressOk() ([]HostIP, bool) {
	if o == nil {
		return nil, false
	}
	return o.IpAddress, true
}

// SetIpAddress sets field value
func (o *Host) SetIpAddress(v []HostIP) {
	o.IpAddress = v
}

// GetBrand returns the Brand field value
func (o *Host) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *Host) GetBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *Host) SetBrand(v string) {
	o.Brand = v
}

// GetModel returns the Model field value
func (o *Host) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Host) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Host) SetModel(v string) {
	o.Model = v
}

// GetNumCpu returns the NumCpu field value
func (o *Host) GetNumCpu() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumCpu
}

// GetNumCpuOk returns a tuple with the NumCpu field value
// and a boolean to check if the value has been set.
func (o *Host) GetNumCpuOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumCpu, true
}

// SetNumCpu sets field value
func (o *Host) SetNumCpu(v int32) {
	o.NumCpu = v
}

// GetCpuInfo returns the CpuInfo field value
func (o *Host) GetCpuInfo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CpuInfo
}

// GetCpuInfoOk returns a tuple with the CpuInfo field value
// and a boolean to check if the value has been set.
func (o *Host) GetCpuInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuInfo, true
}

// SetCpuInfo sets field value
func (o *Host) SetCpuInfo(v string) {
	o.CpuInfo = v
}

// GetCpuType returns the CpuType field value
func (o *Host) GetCpuType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CpuType
}

// GetCpuTypeOk returns a tuple with the CpuType field value
// and a boolean to check if the value has been set.
func (o *Host) GetCpuTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuType, true
}

// SetCpuType sets field value
func (o *Host) SetCpuType(v string) {
	o.CpuType = v
}

// GetCpuLoad returns the CpuLoad field value
func (o *Host) GetCpuLoad() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CpuLoad
}

// GetCpuLoadOk returns a tuple with the CpuLoad field value
// and a boolean to check if the value has been set.
func (o *Host) GetCpuLoadOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuLoad, true
}

// SetCpuLoad sets field value
func (o *Host) SetCpuLoad(v float32) {
	o.CpuLoad = v
}

// GetCpu returns the Cpu field value
func (o *Host) GetCpu() HostCpu {
	if o == nil {
		var ret HostCpu
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *Host) GetCpuOk() (*HostCpu, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *Host) SetCpu(v HostCpu) {
	o.Cpu = v
}

// GetMemUsed returns the MemUsed field value
func (o *Host) GetMemUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemUsed
}

// GetMemUsedOk returns a tuple with the MemUsed field value
// and a boolean to check if the value has been set.
func (o *Host) GetMemUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemUsed, true
}

// SetMemUsed sets field value
func (o *Host) SetMemUsed(v int32) {
	o.MemUsed = v
}

// GetMemMax returns the MemMax field value
func (o *Host) GetMemMax() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemMax
}

// GetMemMaxOk returns a tuple with the MemMax field value
// and a boolean to check if the value has been set.
func (o *Host) GetMemMaxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemMax, true
}

// SetMemMax sets field value
func (o *Host) SetMemMax(v int32) {
	o.MemMax = v
}

// GetMemFree returns the MemFree field value
func (o *Host) GetMemFree() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemFree
}

// GetMemFreeOk returns a tuple with the MemFree field value
// and a boolean to check if the value has been set.
func (o *Host) GetMemFreeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemFree, true
}

// SetMemFree sets field value
func (o *Host) SetMemFree(v int32) {
	o.MemFree = v
}

// GetDisk returns the Disk field value
func (o *Host) GetDisk() []HostDisk {
	if o == nil {
		var ret []HostDisk
		return ret
	}

	return o.Disk
}

// GetDiskOk returns a tuple with the Disk field value
// and a boolean to check if the value has been set.
func (o *Host) GetDiskOk() ([]HostDisk, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disk, true
}

// SetDisk sets field value
func (o *Host) SetDisk(v []HostDisk) {
	o.Disk = v
}

// GetMemory returns the Memory field value
func (o *Host) GetMemory() []HostMemory {
	if o == nil {
		var ret []HostMemory
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *Host) GetMemoryOk() ([]HostMemory, bool) {
	if o == nil {
		return nil, false
	}
	return o.Memory, true
}

// SetMemory sets field value
func (o *Host) SetMemory(v []HostMemory) {
	o.Memory = v
}

// GetIsReserve returns the IsReserve field value
func (o *Host) GetIsReserve() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IsReserve
}

// GetIsReserveOk returns a tuple with the IsReserve field value
// and a boolean to check if the value has been set.
func (o *Host) GetIsReserveOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsReserve, true
}

// SetIsReserve sets field value
func (o *Host) SetIsReserve(v int32) {
	o.IsReserve = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Host) GetLabels() []Label {
	if o == nil || IsNil(o.Labels) {
		var ret []Label
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetLabelsOk() ([]Label, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Host) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []Label and assigns it to the Labels field.
func (o *Host) SetLabels(v []Label) {
	o.Labels = v
}

// GetServiceTag returns the ServiceTag field value
func (o *Host) GetServiceTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceTag
}

// GetServiceTagOk returns a tuple with the ServiceTag field value
// and a boolean to check if the value has been set.
func (o *Host) GetServiceTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceTag, true
}

// SetServiceTag sets field value
func (o *Host) SetServiceTag(v string) {
	o.ServiceTag = v
}

// GetIsODP returns the IsODP field value
func (o *Host) GetIsODP() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IsODP
}

// GetIsODPOk returns a tuple with the IsODP field value
// and a boolean to check if the value has been set.
func (o *Host) GetIsODPOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsODP, true
}

// SetIsODP sets field value
func (o *Host) SetIsODP(v int32) {
	o.IsODP = v
}

// GetFmOrderId returns the FmOrderId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Host) GetFmOrderId() string {
	if o == nil || o.FmOrderId.Get() == nil {
		var ret string
		return ret
	}

	return *o.FmOrderId.Get()
}

// GetFmOrderIdOk returns a tuple with the FmOrderId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Host) GetFmOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FmOrderId.Get(), o.FmOrderId.IsSet()
}

// SetFmOrderId sets field value
func (o *Host) SetFmOrderId(v string) {
	o.FmOrderId.Set(&v)
}

// GetInstallStatus returns the InstallStatus field value
// If the value is explicit nil, the zero value for string will be returned
func (o *Host) GetInstallStatus() string {
	if o == nil || o.InstallStatus.Get() == nil {
		var ret string
		return ret
	}

	return *o.InstallStatus.Get()
}

// GetInstallStatusOk returns a tuple with the InstallStatus field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Host) GetInstallStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstallStatus.Get(), o.InstallStatus.IsSet()
}

// SetInstallStatus sets field value
func (o *Host) SetInstallStatus(v string) {
	o.InstallStatus.Set(&v)
}

// GetStatus returns the Status field value
func (o *Host) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Host) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Host) SetStatus(v string) {
	o.Status = v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *Host) GetUptime() int32 {
	if o == nil || IsNil(o.Uptime) {
		var ret int32
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetUptimeOk() (*int32, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *Host) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int32 and assigns it to the Uptime field.
func (o *Host) SetUptime(v int32) {
	o.Uptime = &v
}

// GetTrafficSum returns the TrafficSum field value
func (o *Host) GetTrafficSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TrafficSum
}

// GetTrafficSumOk returns a tuple with the TrafficSum field value
// and a boolean to check if the value has been set.
func (o *Host) GetTrafficSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrafficSum, true
}

// SetTrafficSum sets field value
func (o *Host) SetTrafficSum(v int32) {
	o.TrafficSum = v
}

// GetUplinks returns the Uplinks field value
func (o *Host) GetUplinks() []HostUplink {
	if o == nil {
		var ret []HostUplink
		return ret
	}

	return o.Uplinks
}

// GetUplinksOk returns a tuple with the Uplinks field value
// and a boolean to check if the value has been set.
func (o *Host) GetUplinksOk() ([]HostUplink, bool) {
	if o == nil {
		return nil, false
	}
	return o.Uplinks, true
}

// SetUplinks sets field value
func (o *Host) SetUplinks(v []HostUplink) {
	o.Uplinks = v
}

// GetFreeIncomingTraffic returns the FreeIncomingTraffic field value
func (o *Host) GetFreeIncomingTraffic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FreeIncomingTraffic
}

// GetFreeIncomingTrafficOk returns a tuple with the FreeIncomingTraffic field value
// and a boolean to check if the value has been set.
func (o *Host) GetFreeIncomingTrafficOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeIncomingTraffic, true
}

// SetFreeIncomingTraffic sets field value
func (o *Host) SetFreeIncomingTraffic(v bool) {
	o.FreeIncomingTraffic = v
}

// GetOutgoingTrafficSum returns the OutgoingTrafficSum field value
func (o *Host) GetOutgoingTrafficSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OutgoingTrafficSum
}

// GetOutgoingTrafficSumOk returns a tuple with the OutgoingTrafficSum field value
// and a boolean to check if the value has been set.
func (o *Host) GetOutgoingTrafficSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutgoingTrafficSum, true
}

// SetOutgoingTrafficSum sets field value
func (o *Host) SetOutgoingTrafficSum(v int32) {
	o.OutgoingTrafficSum = v
}

// GetIncomingTrafficSum returns the IncomingTrafficSum field value
func (o *Host) GetIncomingTrafficSum() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IncomingTrafficSum
}

// GetIncomingTrafficSumOk returns a tuple with the IncomingTrafficSum field value
// and a boolean to check if the value has been set.
func (o *Host) GetIncomingTrafficSumOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IncomingTrafficSum, true
}

// SetIncomingTrafficSum sets field value
func (o *Host) SetIncomingTrafficSum(v int32) {
	o.IncomingTrafficSum = v
}

func (o Host) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Host) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["userId"] = o.UserId
	toSerialize["serverId"] = o.ServerId
	toSerialize["serverName"] = o.ServerName
	toSerialize["serverType"] = o.ServerType
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	if !IsNil(o.ClientServerName) {
		toSerialize["clientServerName"] = o.ClientServerName
	}
	if !IsNil(o.ClientState) {
		toSerialize["clientState"] = o.ClientState
	}
	toSerialize["liveHostName"] = o.LiveHostName
	toSerialize["isVirtual"] = o.IsVirtual
	toSerialize["category"] = o.Category
	toSerialize["osId"] = o.OsId
	toSerialize["locationId"] = o.LocationId
	toSerialize["dcLocationId"] = o.DcLocationId
	toSerialize["instanceType"] = o.InstanceType
	toSerialize["fleetId"] = o.FleetId
	toSerialize["newFleetId"] = o.NewFleetId.Get()
	toSerialize["fleetAssociatedSince"] = o.FleetAssociatedSince
	toSerialize["rackName"] = o.RackName
	toSerialize["dateStart"] = o.DateStart
	toSerialize["dateEnd"] = o.DateEnd
	toSerialize["dateCancelled"] = o.DateCancelled
	toSerialize["dateEndContract"] = o.DateEndContract
	toSerialize["contractPeriod"] = o.ContractPeriod
	toSerialize["extendPeriod"] = o.ExtendPeriod
	toSerialize["cancellationPeriod"] = o.CancellationPeriod
	toSerialize["purchaseOrder"] = o.PurchaseOrder
	toSerialize["paymentTerm"] = o.PaymentTerm
	toSerialize["pricePerMonth"] = o.PricePerMonth
	toSerialize["pricePerTbOveruse"] = o.PricePerTbOveruse
	toSerialize["currencyId"] = o.CurrencyId
	toSerialize["bandwidthBillingType"] = o.BandwidthBillingType
	toSerialize["bandwidthContractual"] = o.BandwidthContractual
	toSerialize["ipAddress"] = o.IpAddress
	toSerialize["brand"] = o.Brand
	toSerialize["model"] = o.Model
	toSerialize["numCpu"] = o.NumCpu
	toSerialize["cpuInfo"] = o.CpuInfo
	toSerialize["cpuType"] = o.CpuType
	toSerialize["cpuLoad"] = o.CpuLoad
	toSerialize["cpu"] = o.Cpu
	toSerialize["memUsed"] = o.MemUsed
	toSerialize["memMax"] = o.MemMax
	toSerialize["memFree"] = o.MemFree
	toSerialize["disk"] = o.Disk
	toSerialize["memory"] = o.Memory
	toSerialize["isReserve"] = o.IsReserve
	if !IsNil(o.Labels) {
		toSerialize["filters"] = o.Labels
	}
	toSerialize["serviceTag"] = o.ServiceTag
	toSerialize["isODP"] = o.IsODP
	toSerialize["fmOrderId"] = o.FmOrderId.Get()
	toSerialize["installStatus"] = o.InstallStatus.Get()
	toSerialize["status"] = o.Status
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	toSerialize["trafficSum"] = o.TrafficSum
	toSerialize["uplinks"] = o.Uplinks
	toSerialize["freeIncomingTraffic"] = o.FreeIncomingTraffic
	toSerialize["outgoingTrafficSum"] = o.OutgoingTrafficSum
	toSerialize["incomingTrafficSum"] = o.IncomingTrafficSum
	return toSerialize, nil
}

func (o *Host) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"userId",
		"serverId",
		"serverName",
		"serverType",
		"liveHostName",
		"isVirtual",
		"category",
		"osId",
		"locationId",
		"dcLocationId",
		"instanceType",
		"fleetId",
		"newFleetId",
		"fleetAssociatedSince",
		"rackName",
		"dateStart",
		"dateEnd",
		"dateCancelled",
		"dateEndContract",
		"contractPeriod",
		"extendPeriod",
		"cancellationPeriod",
		"purchaseOrder",
		"paymentTerm",
		"pricePerMonth",
		"pricePerTbOveruse",
		"currencyId",
		"bandwidthBillingType",
		"bandwidthContractual",
		"ipAddress",
		"brand",
		"model",
		"numCpu",
		"cpuInfo",
		"cpuType",
		"cpuLoad",
		"cpu",
		"memUsed",
		"memMax",
		"memFree",
		"disk",
		"memory",
		"isReserve",
		"serviceTag",
		"isODP",
		"fmOrderId",
		"installStatus",
		"status",
		"trafficSum",
		"uplinks",
		"freeIncomingTraffic",
		"outgoingTrafficSum",
		"incomingTrafficSum",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHost := _Host{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHost)

	if err != nil {
		return err
	}

	*o = Host(varHost)

	return err
}

type NullableHost struct {
	value *Host
	isSet bool
}

func (v NullableHost) Get() *Host {
	return v.value
}

func (v *NullableHost) Set(val *Host) {
	v.value = val
	v.isSet = true
}

func (v NullableHost) IsSet() bool {
	return v.isSet
}

func (v *NullableHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHost(val *Host) *NullableHost {
	return &NullableHost{value: val, isSet: true}
}

func (v NullableHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
