/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BuildProvisioningRegistrationType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildProvisioningRegistrationType{}

// BuildProvisioningRegistrationType struct for BuildProvisioningRegistrationType
type BuildProvisioningRegistrationType struct {
	// ID of the build provisioning registration type
	Id int32 `json:"id"`
	// Description of the build provisioning registration type
	Description string `json:"description"`
}

type _BuildProvisioningRegistrationType BuildProvisioningRegistrationType

// NewBuildProvisioningRegistrationType instantiates a new BuildProvisioningRegistrationType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildProvisioningRegistrationType(id int32, description string) *BuildProvisioningRegistrationType {
	this := BuildProvisioningRegistrationType{}
	this.Id = id
	this.Description = description
	return &this
}

// NewBuildProvisioningRegistrationTypeWithDefaults instantiates a new BuildProvisioningRegistrationType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildProvisioningRegistrationTypeWithDefaults() *BuildProvisioningRegistrationType {
	this := BuildProvisioningRegistrationType{}
	return &this
}

// GetId returns the Id field value
func (o *BuildProvisioningRegistrationType) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningRegistrationType) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BuildProvisioningRegistrationType) SetId(v int32) {
	o.Id = v
}

// GetDescription returns the Description field value
func (o *BuildProvisioningRegistrationType) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningRegistrationType) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *BuildProvisioningRegistrationType) SetDescription(v string) {
	o.Description = v
}

func (o BuildProvisioningRegistrationType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildProvisioningRegistrationType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *BuildProvisioningRegistrationType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildProvisioningRegistrationType := _BuildProvisioningRegistrationType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildProvisioningRegistrationType)

	if err != nil {
		return err
	}

	*o = BuildProvisioningRegistrationType(varBuildProvisioningRegistrationType)

	return err
}

type NullableBuildProvisioningRegistrationType struct {
	value *BuildProvisioningRegistrationType
	isSet bool
}

func (v NullableBuildProvisioningRegistrationType) Get() *BuildProvisioningRegistrationType {
	return v.value
}

func (v *NullableBuildProvisioningRegistrationType) Set(val *BuildProvisioningRegistrationType) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildProvisioningRegistrationType) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildProvisioningRegistrationType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildProvisioningRegistrationType(val *BuildProvisioningRegistrationType) *NullableBuildProvisioningRegistrationType {
	return &NullableBuildProvisioningRegistrationType{value: val, isSet: true}
}

func (v NullableBuildProvisioningRegistrationType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildProvisioningRegistrationType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
