/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PatchJobType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchJobType{}

// PatchJobType struct for PatchJobType
type PatchJobType struct {
	// Patch job type ID
	TypeId int32 `json:"typeId"`
	// Patch job type description
	TypeDescription string `json:"typeDescription"`
}

type _PatchJobType PatchJobType

// NewPatchJobType instantiates a new PatchJobType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchJobType(typeId int32, typeDescription string) *PatchJobType {
	this := PatchJobType{}
	this.TypeId = typeId
	this.TypeDescription = typeDescription
	return &this
}

// NewPatchJobTypeWithDefaults instantiates a new PatchJobType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchJobTypeWithDefaults() *PatchJobType {
	this := PatchJobType{}
	return &this
}

// GetTypeId returns the TypeId field value
func (o *PatchJobType) GetTypeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value
// and a boolean to check if the value has been set.
func (o *PatchJobType) GetTypeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeId, true
}

// SetTypeId sets field value
func (o *PatchJobType) SetTypeId(v int32) {
	o.TypeId = v
}

// GetTypeDescription returns the TypeDescription field value
func (o *PatchJobType) GetTypeDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TypeDescription
}

// GetTypeDescriptionOk returns a tuple with the TypeDescription field value
// and a boolean to check if the value has been set.
func (o *PatchJobType) GetTypeDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TypeDescription, true
}

// SetTypeDescription sets field value
func (o *PatchJobType) SetTypeDescription(v string) {
	o.TypeDescription = v
}

func (o PatchJobType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchJobType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["typeId"] = o.TypeId
	toSerialize["typeDescription"] = o.TypeDescription
	return toSerialize, nil
}

func (o *PatchJobType) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"typeId",
		"typeDescription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchJobType := _PatchJobType{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchJobType)

	if err != nil {
		return err
	}

	*o = PatchJobType(varPatchJobType)

	return err
}

type NullablePatchJobType struct {
	value *PatchJobType
	isSet bool
}

func (v NullablePatchJobType) Get() *PatchJobType {
	return v.value
}

func (v *NullablePatchJobType) Set(val *PatchJobType) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchJobType) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchJobType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchJobType(val *PatchJobType) *NullablePatchJobType {
	return &NullablePatchJobType{value: val, isSet: true}
}

func (v NullablePatchJobType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchJobType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
