/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceLogModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceLogModel{}

// ApplicationInstanceLogModel struct for ApplicationInstanceLogModel
type ApplicationInstanceLogModel struct {
	// ID of Application instance
	ApplicationInstanceId string `json:"applicationInstanceId"`
	// The application instance's fleet ID
	FleetId string `json:"fleetId"`
	// The code given back by the server when the application instance was killed
	ExitCode int32 `json:"exitCode"`
	// Log output from the application instances from the server
	StdOutLog string `json:"stdOutLog"`
	// Timestamp when the log was created
	CreatedAt int32 `json:"createdAt"`
}

type _ApplicationInstanceLogModel ApplicationInstanceLogModel

// NewApplicationInstanceLogModel instantiates a new ApplicationInstanceLogModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceLogModel(applicationInstanceId string, fleetId string, exitCode int32, stdOutLog string, createdAt int32) *ApplicationInstanceLogModel {
	this := ApplicationInstanceLogModel{}
	this.ApplicationInstanceId = applicationInstanceId
	this.FleetId = fleetId
	this.ExitCode = exitCode
	this.StdOutLog = stdOutLog
	this.CreatedAt = createdAt
	return &this
}

// NewApplicationInstanceLogModelWithDefaults instantiates a new ApplicationInstanceLogModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceLogModelWithDefaults() *ApplicationInstanceLogModel {
	this := ApplicationInstanceLogModel{}
	return &this
}

// GetApplicationInstanceId returns the ApplicationInstanceId field value
func (o *ApplicationInstanceLogModel) GetApplicationInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationInstanceId
}

// GetApplicationInstanceIdOk returns a tuple with the ApplicationInstanceId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceLogModel) GetApplicationInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationInstanceId, true
}

// SetApplicationInstanceId sets field value
func (o *ApplicationInstanceLogModel) SetApplicationInstanceId(v string) {
	o.ApplicationInstanceId = v
}

// GetFleetId returns the FleetId field value
func (o *ApplicationInstanceLogModel) GetFleetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FleetId
}

// GetFleetIdOk returns a tuple with the FleetId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceLogModel) GetFleetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FleetId, true
}

// SetFleetId sets field value
func (o *ApplicationInstanceLogModel) SetFleetId(v string) {
	o.FleetId = v
}

// GetExitCode returns the ExitCode field value
func (o *ApplicationInstanceLogModel) GetExitCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExitCode
}

// GetExitCodeOk returns a tuple with the ExitCode field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceLogModel) GetExitCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExitCode, true
}

// SetExitCode sets field value
func (o *ApplicationInstanceLogModel) SetExitCode(v int32) {
	o.ExitCode = v
}

// GetStdOutLog returns the StdOutLog field value
func (o *ApplicationInstanceLogModel) GetStdOutLog() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StdOutLog
}

// GetStdOutLogOk returns a tuple with the StdOutLog field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceLogModel) GetStdOutLogOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StdOutLog, true
}

// SetStdOutLog sets field value
func (o *ApplicationInstanceLogModel) SetStdOutLog(v string) {
	o.StdOutLog = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ApplicationInstanceLogModel) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceLogModel) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ApplicationInstanceLogModel) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

func (o ApplicationInstanceLogModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceLogModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationInstanceId"] = o.ApplicationInstanceId
	toSerialize["fleetId"] = o.FleetId
	toSerialize["exitCode"] = o.ExitCode
	toSerialize["stdOutLog"] = o.StdOutLog
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ApplicationInstanceLogModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationInstanceId",
		"fleetId",
		"exitCode",
		"stdOutLog",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceLogModel := _ApplicationInstanceLogModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceLogModel)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceLogModel(varApplicationInstanceLogModel)

	return err
}

type NullableApplicationInstanceLogModel struct {
	value *ApplicationInstanceLogModel
	isSet bool
}

func (v NullableApplicationInstanceLogModel) Get() *ApplicationInstanceLogModel {
	return v.value
}

func (v *NullableApplicationInstanceLogModel) Set(val *ApplicationInstanceLogModel) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceLogModel) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceLogModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceLogModel(val *ApplicationInstanceLogModel) *NullableApplicationInstanceLogModel {
	return &NullableApplicationInstanceLogModel{value: val, isSet: true}
}

func (v NullableApplicationInstanceLogModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceLogModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
