/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceCpuTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceCpuTelemetry{}

// ApplicationInstanceCpuTelemetry struct for ApplicationInstanceCpuTelemetry
type ApplicationInstanceCpuTelemetry struct {
	// Unit of data frequency, which is always `null` in this endpoint. This property is there for consistency across all telemetry endpoints. It's `null` because the data is not aggregated
	Unit string `json:"unit"`
	// Contains the data object
	Data []ApplicationInstanceCpuDataTelemetry `json:"data"`
}

type _ApplicationInstanceCpuTelemetry ApplicationInstanceCpuTelemetry

// NewApplicationInstanceCpuTelemetry instantiates a new ApplicationInstanceCpuTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceCpuTelemetry(unit string, data []ApplicationInstanceCpuDataTelemetry) *ApplicationInstanceCpuTelemetry {
	this := ApplicationInstanceCpuTelemetry{}
	this.Unit = unit
	this.Data = data
	return &this
}

// NewApplicationInstanceCpuTelemetryWithDefaults instantiates a new ApplicationInstanceCpuTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceCpuTelemetryWithDefaults() *ApplicationInstanceCpuTelemetry {
	this := ApplicationInstanceCpuTelemetry{}
	return &this
}

// GetUnit returns the Unit field value
func (o *ApplicationInstanceCpuTelemetry) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceCpuTelemetry) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *ApplicationInstanceCpuTelemetry) SetUnit(v string) {
	o.Unit = v
}

// GetData returns the Data field value
func (o *ApplicationInstanceCpuTelemetry) GetData() []ApplicationInstanceCpuDataTelemetry {
	if o == nil {
		var ret []ApplicationInstanceCpuDataTelemetry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceCpuTelemetry) GetDataOk() ([]ApplicationInstanceCpuDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApplicationInstanceCpuTelemetry) SetData(v []ApplicationInstanceCpuDataTelemetry) {
	o.Data = v
}

func (o ApplicationInstanceCpuTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceCpuTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unit"] = o.Unit
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApplicationInstanceCpuTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceCpuTelemetry := _ApplicationInstanceCpuTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceCpuTelemetry)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceCpuTelemetry(varApplicationInstanceCpuTelemetry)

	return err
}

type NullableApplicationInstanceCpuTelemetry struct {
	value *ApplicationInstanceCpuTelemetry
	isSet bool
}

func (v NullableApplicationInstanceCpuTelemetry) Get() *ApplicationInstanceCpuTelemetry {
	return v.value
}

func (v *NullableApplicationInstanceCpuTelemetry) Set(val *ApplicationInstanceCpuTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceCpuTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceCpuTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceCpuTelemetry(val *ApplicationInstanceCpuTelemetry) *NullableApplicationInstanceCpuTelemetry {
	return &NullableApplicationInstanceCpuTelemetry{value: val, isSet: true}
}

func (v NullableApplicationInstanceCpuTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceCpuTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
