/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstancesTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstancesTelemetry{}

// ApplicationInstancesTelemetry struct for ApplicationInstancesTelemetry
type ApplicationInstancesTelemetry struct {
	// Unit of data frequency,  possible interval options are as follows - minute - hour - day - week
	Unit string `json:"unit"`
	// Average aggregated data of application instances
	Data []ApplicationInstancesDataTelemetry `json:"data"`
}

type _ApplicationInstancesTelemetry ApplicationInstancesTelemetry

// NewApplicationInstancesTelemetry instantiates a new ApplicationInstancesTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstancesTelemetry(unit string, data []ApplicationInstancesDataTelemetry) *ApplicationInstancesTelemetry {
	this := ApplicationInstancesTelemetry{}
	this.Unit = unit
	this.Data = data
	return &this
}

// NewApplicationInstancesTelemetryWithDefaults instantiates a new ApplicationInstancesTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstancesTelemetryWithDefaults() *ApplicationInstancesTelemetry {
	this := ApplicationInstancesTelemetry{}
	return &this
}

// GetUnit returns the Unit field value
func (o *ApplicationInstancesTelemetry) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstancesTelemetry) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *ApplicationInstancesTelemetry) SetUnit(v string) {
	o.Unit = v
}

// GetData returns the Data field value
func (o *ApplicationInstancesTelemetry) GetData() []ApplicationInstancesDataTelemetry {
	if o == nil {
		var ret []ApplicationInstancesDataTelemetry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstancesTelemetry) GetDataOk() ([]ApplicationInstancesDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApplicationInstancesTelemetry) SetData(v []ApplicationInstancesDataTelemetry) {
	o.Data = v
}

func (o ApplicationInstancesTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstancesTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unit"] = o.Unit
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApplicationInstancesTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstancesTelemetry := _ApplicationInstancesTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstancesTelemetry)

	if err != nil {
		return err
	}

	*o = ApplicationInstancesTelemetry(varApplicationInstancesTelemetry)

	return err
}

type NullableApplicationInstancesTelemetry struct {
	value *ApplicationInstancesTelemetry
	isSet bool
}

func (v NullableApplicationInstancesTelemetry) Get() *ApplicationInstancesTelemetry {
	return v.value
}

func (v *NullableApplicationInstancesTelemetry) Set(val *ApplicationInstancesTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstancesTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstancesTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstancesTelemetry(val *ApplicationInstancesTelemetry) *NullableApplicationInstancesTelemetry {
	return &NullableApplicationInstancesTelemetry{value: val, isSet: true}
}

func (v NullableApplicationInstancesTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstancesTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
