/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PatchJobFleetApplicationBuild type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchJobFleetApplicationBuild{}

// PatchJobFleetApplicationBuild struct for PatchJobFleetApplicationBuild
type PatchJobFleetApplicationBuild struct {
	// ID of the fleet
	Id string `json:"id"`
	// Name of the fleet
	Name string `json:"name"`
	// Array of the application build belonging to the fleet
	ApplicationBuild []PatchJobFleetApplicationBuildDetail `json:"applicationBuild"`
}

type _PatchJobFleetApplicationBuild PatchJobFleetApplicationBuild

// NewPatchJobFleetApplicationBuild instantiates a new PatchJobFleetApplicationBuild object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchJobFleetApplicationBuild(id string, name string, applicationBuild []PatchJobFleetApplicationBuildDetail) *PatchJobFleetApplicationBuild {
	this := PatchJobFleetApplicationBuild{}
	this.Id = id
	this.Name = name
	this.ApplicationBuild = applicationBuild
	return &this
}

// NewPatchJobFleetApplicationBuildWithDefaults instantiates a new PatchJobFleetApplicationBuild object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchJobFleetApplicationBuildWithDefaults() *PatchJobFleetApplicationBuild {
	this := PatchJobFleetApplicationBuild{}
	return &this
}

// GetId returns the Id field value
func (o *PatchJobFleetApplicationBuild) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchJobFleetApplicationBuild) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchJobFleetApplicationBuild) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PatchJobFleetApplicationBuild) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PatchJobFleetApplicationBuild) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PatchJobFleetApplicationBuild) SetName(v string) {
	o.Name = v
}

// GetApplicationBuild returns the ApplicationBuild field value
func (o *PatchJobFleetApplicationBuild) GetApplicationBuild() []PatchJobFleetApplicationBuildDetail {
	if o == nil {
		var ret []PatchJobFleetApplicationBuildDetail
		return ret
	}

	return o.ApplicationBuild
}

// GetApplicationBuildOk returns a tuple with the ApplicationBuild field value
// and a boolean to check if the value has been set.
func (o *PatchJobFleetApplicationBuild) GetApplicationBuildOk() ([]PatchJobFleetApplicationBuildDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationBuild, true
}

// SetApplicationBuild sets field value
func (o *PatchJobFleetApplicationBuild) SetApplicationBuild(v []PatchJobFleetApplicationBuildDetail) {
	o.ApplicationBuild = v
}

func (o PatchJobFleetApplicationBuild) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchJobFleetApplicationBuild) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["applicationBuild"] = o.ApplicationBuild
	return toSerialize, nil
}

func (o *PatchJobFleetApplicationBuild) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"applicationBuild",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchJobFleetApplicationBuild := _PatchJobFleetApplicationBuild{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchJobFleetApplicationBuild)

	if err != nil {
		return err
	}

	*o = PatchJobFleetApplicationBuild(varPatchJobFleetApplicationBuild)

	return err
}

type NullablePatchJobFleetApplicationBuild struct {
	value *PatchJobFleetApplicationBuild
	isSet bool
}

func (v NullablePatchJobFleetApplicationBuild) Get() *PatchJobFleetApplicationBuild {
	return v.value
}

func (v *NullablePatchJobFleetApplicationBuild) Set(val *PatchJobFleetApplicationBuild) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchJobFleetApplicationBuild) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchJobFleetApplicationBuild) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchJobFleetApplicationBuild(val *PatchJobFleetApplicationBuild) *NullablePatchJobFleetApplicationBuild {
	return &NullablePatchJobFleetApplicationBuild{value: val, isSet: true}
}

func (v NullablePatchJobFleetApplicationBuild) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchJobFleetApplicationBuild) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
