/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CloudCredentialsParamsAzure type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudCredentialsParamsAzure{}

// CloudCredentialsParamsAzure struct for CloudCredentialsParamsAzure
type CloudCredentialsParamsAzure struct {
	TenantId        string `json:"tenantId"`
	SubscriptionId  string `json:"subscriptionId"`
	ClientId        string `json:"clientId"`
	ClientSecretKey string `json:"clientSecretKey"`
	ResourceName    string `json:"resourceName"`
	// (regionName from [`GET /v3/cloud/provider/28/dcLocation`](#/Cloud/get_v3_cloud_provider__providerId__dcLocation))
	DefaultRegion string `json:"defaultRegion"`
}

type _CloudCredentialsParamsAzure CloudCredentialsParamsAzure

// NewCloudCredentialsParamsAzure instantiates a new CloudCredentialsParamsAzure object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudCredentialsParamsAzure(tenantId string, subscriptionId string, clientId string, clientSecretKey string, resourceName string, defaultRegion string) *CloudCredentialsParamsAzure {
	this := CloudCredentialsParamsAzure{}
	this.TenantId = tenantId
	this.SubscriptionId = subscriptionId
	this.ClientId = clientId
	this.ClientSecretKey = clientSecretKey
	this.ResourceName = resourceName
	this.DefaultRegion = defaultRegion
	return &this
}

// NewCloudCredentialsParamsAzureWithDefaults instantiates a new CloudCredentialsParamsAzure object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudCredentialsParamsAzureWithDefaults() *CloudCredentialsParamsAzure {
	this := CloudCredentialsParamsAzure{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *CloudCredentialsParamsAzure) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CloudCredentialsParamsAzure) SetTenantId(v string) {
	o.TenantId = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *CloudCredentialsParamsAzure) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *CloudCredentialsParamsAzure) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetClientId returns the ClientId field value
func (o *CloudCredentialsParamsAzure) GetClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *CloudCredentialsParamsAzure) SetClientId(v string) {
	o.ClientId = v
}

// GetClientSecretKey returns the ClientSecretKey field value
func (o *CloudCredentialsParamsAzure) GetClientSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientSecretKey
}

// GetClientSecretKeyOk returns a tuple with the ClientSecretKey field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetClientSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientSecretKey, true
}

// SetClientSecretKey sets field value
func (o *CloudCredentialsParamsAzure) SetClientSecretKey(v string) {
	o.ClientSecretKey = v
}

// GetResourceName returns the ResourceName field value
func (o *CloudCredentialsParamsAzure) GetResourceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceName
}

// GetResourceNameOk returns a tuple with the ResourceName field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetResourceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceName, true
}

// SetResourceName sets field value
func (o *CloudCredentialsParamsAzure) SetResourceName(v string) {
	o.ResourceName = v
}

// GetDefaultRegion returns the DefaultRegion field value
func (o *CloudCredentialsParamsAzure) GetDefaultRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultRegion
}

// GetDefaultRegionOk returns a tuple with the DefaultRegion field value
// and a boolean to check if the value has been set.
func (o *CloudCredentialsParamsAzure) GetDefaultRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultRegion, true
}

// SetDefaultRegion sets field value
func (o *CloudCredentialsParamsAzure) SetDefaultRegion(v string) {
	o.DefaultRegion = v
}

func (o CloudCredentialsParamsAzure) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudCredentialsParamsAzure) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["subscriptionId"] = o.SubscriptionId
	toSerialize["clientId"] = o.ClientId
	toSerialize["clientSecretKey"] = o.ClientSecretKey
	toSerialize["resourceName"] = o.ResourceName
	toSerialize["defaultRegion"] = o.DefaultRegion
	return toSerialize, nil
}

func (o *CloudCredentialsParamsAzure) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"subscriptionId",
		"clientId",
		"clientSecretKey",
		"resourceName",
		"defaultRegion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudCredentialsParamsAzure := _CloudCredentialsParamsAzure{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudCredentialsParamsAzure)

	if err != nil {
		return err
	}

	*o = CloudCredentialsParamsAzure(varCloudCredentialsParamsAzure)

	return err
}

type NullableCloudCredentialsParamsAzure struct {
	value *CloudCredentialsParamsAzure
	isSet bool
}

func (v NullableCloudCredentialsParamsAzure) Get() *CloudCredentialsParamsAzure {
	return v.value
}

func (v *NullableCloudCredentialsParamsAzure) Set(val *CloudCredentialsParamsAzure) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudCredentialsParamsAzure) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudCredentialsParamsAzure) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudCredentialsParamsAzure(val *CloudCredentialsParamsAzure) *NullableCloudCredentialsParamsAzure {
	return &NullableCloudCredentialsParamsAzure{value: val, isSet: true}
}

func (v NullableCloudCredentialsParamsAzure) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudCredentialsParamsAzure) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
