/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceConfiguration{}

// ApplicationInstanceConfiguration struct for ApplicationInstanceConfiguration
type ApplicationInstanceConfiguration struct {
	// The ID of the application instance configuration
	Id string `json:"id"`
	// The ID of the application instance
	ApplicationInstanceId string `json:"applicationInstanceId"`
	// The ID of the application build configuration
	ApplicationBuildConfigurationId string `json:"applicationBuildConfigurationId"`
	// Path of the configuration
	ConfigPath string `json:"configPath"`
	// Name of the configuration
	ConfigName string `json:"configName"`
	// Content of the configuration
	ConfigContent string `json:"configContent"`
	// UnixTimestamp
	UpdatedAt int32 `json:"updatedAt"`
	// Status of the application instance configuration
	Active int32 `json:"active"`
}

type _ApplicationInstanceConfiguration ApplicationInstanceConfiguration

// NewApplicationInstanceConfiguration instantiates a new ApplicationInstanceConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceConfiguration(id string, applicationInstanceId string, applicationBuildConfigurationId string, configPath string, configName string, configContent string, updatedAt int32, active int32) *ApplicationInstanceConfiguration {
	this := ApplicationInstanceConfiguration{}
	this.Id = id
	this.ApplicationInstanceId = applicationInstanceId
	this.ApplicationBuildConfigurationId = applicationBuildConfigurationId
	this.ConfigPath = configPath
	this.ConfigName = configName
	this.ConfigContent = configContent
	this.UpdatedAt = updatedAt
	this.Active = active
	return &this
}

// NewApplicationInstanceConfigurationWithDefaults instantiates a new ApplicationInstanceConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceConfigurationWithDefaults() *ApplicationInstanceConfiguration {
	this := ApplicationInstanceConfiguration{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationInstanceConfiguration) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationInstanceConfiguration) SetId(v string) {
	o.Id = v
}

// GetApplicationInstanceId returns the ApplicationInstanceId field value
func (o *ApplicationInstanceConfiguration) GetApplicationInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationInstanceId
}

// GetApplicationInstanceIdOk returns a tuple with the ApplicationInstanceId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetApplicationInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationInstanceId, true
}

// SetApplicationInstanceId sets field value
func (o *ApplicationInstanceConfiguration) SetApplicationInstanceId(v string) {
	o.ApplicationInstanceId = v
}

// GetApplicationBuildConfigurationId returns the ApplicationBuildConfigurationId field value
func (o *ApplicationInstanceConfiguration) GetApplicationBuildConfigurationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationBuildConfigurationId
}

// GetApplicationBuildConfigurationIdOk returns a tuple with the ApplicationBuildConfigurationId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetApplicationBuildConfigurationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationBuildConfigurationId, true
}

// SetApplicationBuildConfigurationId sets field value
func (o *ApplicationInstanceConfiguration) SetApplicationBuildConfigurationId(v string) {
	o.ApplicationBuildConfigurationId = v
}

// GetConfigPath returns the ConfigPath field value
func (o *ApplicationInstanceConfiguration) GetConfigPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigPath
}

// GetConfigPathOk returns a tuple with the ConfigPath field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetConfigPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigPath, true
}

// SetConfigPath sets field value
func (o *ApplicationInstanceConfiguration) SetConfigPath(v string) {
	o.ConfigPath = v
}

// GetConfigName returns the ConfigName field value
func (o *ApplicationInstanceConfiguration) GetConfigName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigName
}

// GetConfigNameOk returns a tuple with the ConfigName field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetConfigNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigName, true
}

// SetConfigName sets field value
func (o *ApplicationInstanceConfiguration) SetConfigName(v string) {
	o.ConfigName = v
}

// GetConfigContent returns the ConfigContent field value
func (o *ApplicationInstanceConfiguration) GetConfigContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConfigContent
}

// GetConfigContentOk returns a tuple with the ConfigContent field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetConfigContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConfigContent, true
}

// SetConfigContent sets field value
func (o *ApplicationInstanceConfiguration) SetConfigContent(v string) {
	o.ConfigContent = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ApplicationInstanceConfiguration) GetUpdatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetUpdatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ApplicationInstanceConfiguration) SetUpdatedAt(v int32) {
	o.UpdatedAt = v
}

// GetActive returns the Active field value
func (o *ApplicationInstanceConfiguration) GetActive() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceConfiguration) GetActiveOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *ApplicationInstanceConfiguration) SetActive(v int32) {
	o.Active = v
}

func (o ApplicationInstanceConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["applicationInstanceId"] = o.ApplicationInstanceId
	toSerialize["applicationBuildConfigurationId"] = o.ApplicationBuildConfigurationId
	toSerialize["configPath"] = o.ConfigPath
	toSerialize["configName"] = o.ConfigName
	toSerialize["configContent"] = o.ConfigContent
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["active"] = o.Active
	return toSerialize, nil
}

func (o *ApplicationInstanceConfiguration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"applicationInstanceId",
		"applicationBuildConfigurationId",
		"configPath",
		"configName",
		"configContent",
		"updatedAt",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceConfiguration := _ApplicationInstanceConfiguration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceConfiguration)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceConfiguration(varApplicationInstanceConfiguration)

	return err
}

type NullableApplicationInstanceConfiguration struct {
	value *ApplicationInstanceConfiguration
	isSet bool
}

func (v NullableApplicationInstanceConfiguration) Get() *ApplicationInstanceConfiguration {
	return v.value
}

func (v *NullableApplicationInstanceConfiguration) Set(val *ApplicationInstanceConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceConfiguration(val *ApplicationInstanceConfiguration) *NullableApplicationInstanceConfiguration {
	return &NullableApplicationInstanceConfiguration{value: val, isSet: true}
}

func (v NullableApplicationInstanceConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
