/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostMemory{}

// HostMemory struct for HostMemory
type HostMemory struct {
	// The brand name
	Brand string `json:"brand"`
	// The model name
	Model string `json:"model"`
	// In bytes
	Size int32 `json:"size"`
	// The speed this memory module runs at
	Speed int32 `json:"speed"`
	// Set to 1 if ecc is supported and enabled
	Ecc int32 `json:"ecc"`
	// The bank this module sits in
	MemoryBank int32 `json:"memoryBank"`
	// The type of memory module
	MemoryType string `json:"memoryType"`
	// The slot this module sits in
	MemorySlot string `json:"memorySlot"`
	// The serial number of this module
	MemorySerial string `json:"memorySerial"`
}

type _HostMemory HostMemory

// NewHostMemory instantiates a new HostMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostMemory(brand string, model string, size int32, speed int32, ecc int32, memoryBank int32, memoryType string, memorySlot string, memorySerial string) *HostMemory {
	this := HostMemory{}
	this.Brand = brand
	this.Model = model
	this.Size = size
	this.Speed = speed
	this.Ecc = ecc
	this.MemoryBank = memoryBank
	this.MemoryType = memoryType
	this.MemorySlot = memorySlot
	this.MemorySerial = memorySerial
	return &this
}

// NewHostMemoryWithDefaults instantiates a new HostMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostMemoryWithDefaults() *HostMemory {
	this := HostMemory{}
	return &this
}

// GetBrand returns the Brand field value
func (o *HostMemory) GetBrand() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Brand
}

// GetBrandOk returns a tuple with the Brand field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetBrandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Brand, true
}

// SetBrand sets field value
func (o *HostMemory) SetBrand(v string) {
	o.Brand = v
}

// GetModel returns the Model field value
func (o *HostMemory) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *HostMemory) SetModel(v string) {
	o.Model = v
}

// GetSize returns the Size field value
func (o *HostMemory) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *HostMemory) SetSize(v int32) {
	o.Size = v
}

// GetSpeed returns the Speed field value
func (o *HostMemory) GetSpeed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Speed
}

// GetSpeedOk returns a tuple with the Speed field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetSpeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Speed, true
}

// SetSpeed sets field value
func (o *HostMemory) SetSpeed(v int32) {
	o.Speed = v
}

// GetEcc returns the Ecc field value
func (o *HostMemory) GetEcc() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ecc
}

// GetEccOk returns a tuple with the Ecc field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetEccOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ecc, true
}

// SetEcc sets field value
func (o *HostMemory) SetEcc(v int32) {
	o.Ecc = v
}

// GetMemoryBank returns the MemoryBank field value
func (o *HostMemory) GetMemoryBank() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryBank
}

// GetMemoryBankOk returns a tuple with the MemoryBank field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetMemoryBankOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryBank, true
}

// SetMemoryBank sets field value
func (o *HostMemory) SetMemoryBank(v int32) {
	o.MemoryBank = v
}

// GetMemoryType returns the MemoryType field value
func (o *HostMemory) GetMemoryType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryType
}

// GetMemoryTypeOk returns a tuple with the MemoryType field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetMemoryTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryType, true
}

// SetMemoryType sets field value
func (o *HostMemory) SetMemoryType(v string) {
	o.MemoryType = v
}

// GetMemorySlot returns the MemorySlot field value
func (o *HostMemory) GetMemorySlot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemorySlot
}

// GetMemorySlotOk returns a tuple with the MemorySlot field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetMemorySlotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemorySlot, true
}

// SetMemorySlot sets field value
func (o *HostMemory) SetMemorySlot(v string) {
	o.MemorySlot = v
}

// GetMemorySerial returns the MemorySerial field value
func (o *HostMemory) GetMemorySerial() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemorySerial
}

// GetMemorySerialOk returns a tuple with the MemorySerial field value
// and a boolean to check if the value has been set.
func (o *HostMemory) GetMemorySerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemorySerial, true
}

// SetMemorySerial sets field value
func (o *HostMemory) SetMemorySerial(v string) {
	o.MemorySerial = v
}

func (o HostMemory) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["brand"] = o.Brand
	toSerialize["model"] = o.Model
	toSerialize["size"] = o.Size
	toSerialize["speed"] = o.Speed
	toSerialize["ecc"] = o.Ecc
	toSerialize["memoryBank"] = o.MemoryBank
	toSerialize["memoryType"] = o.MemoryType
	toSerialize["memorySlot"] = o.MemorySlot
	toSerialize["memorySerial"] = o.MemorySerial
	return toSerialize, nil
}

func (o *HostMemory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"brand",
		"model",
		"size",
		"speed",
		"ecc",
		"memoryBank",
		"memoryType",
		"memorySlot",
		"memorySerial",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostMemory := _HostMemory{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostMemory)

	if err != nil {
		return err
	}

	*o = HostMemory(varHostMemory)

	return err
}

type NullableHostMemory struct {
	value *HostMemory
	isSet bool
}

func (v NullableHostMemory) Get() *HostMemory {
	return v.value
}

func (v *NullableHostMemory) Set(val *HostMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableHostMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableHostMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostMemory(val *HostMemory) *NullableHostMemory {
	return &NullableHostMemory{value: val, isSet: true}
}

func (v NullableHostMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
