/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CCUApplicationTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CCUApplicationTelemetry{}

// CCUApplicationTelemetry struct for CCUApplicationTelemetry
type CCUApplicationTelemetry struct {
	// Application ID
	ApplicationId string `json:"applicationId"`
	// The public name of your application
	ApplicationName string `json:"applicationName"`
	// Number of players currently playing on the hosts
	PlayerCount int32 `json:"playerCount"`
	// Maximum number of players the hosts can support
	MaxPlayers int32 `json:"maxPlayers"`
}

type _CCUApplicationTelemetry CCUApplicationTelemetry

// NewCCUApplicationTelemetry instantiates a new CCUApplicationTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCCUApplicationTelemetry(applicationId string, applicationName string, playerCount int32, maxPlayers int32) *CCUApplicationTelemetry {
	this := CCUApplicationTelemetry{}
	this.ApplicationId = applicationId
	this.ApplicationName = applicationName
	this.PlayerCount = playerCount
	this.MaxPlayers = maxPlayers
	return &this
}

// NewCCUApplicationTelemetryWithDefaults instantiates a new CCUApplicationTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCCUApplicationTelemetryWithDefaults() *CCUApplicationTelemetry {
	this := CCUApplicationTelemetry{}
	return &this
}

// GetApplicationId returns the ApplicationId field value
func (o *CCUApplicationTelemetry) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *CCUApplicationTelemetry) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *CCUApplicationTelemetry) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetApplicationName returns the ApplicationName field value
func (o *CCUApplicationTelemetry) GetApplicationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value
// and a boolean to check if the value has been set.
func (o *CCUApplicationTelemetry) GetApplicationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationName, true
}

// SetApplicationName sets field value
func (o *CCUApplicationTelemetry) SetApplicationName(v string) {
	o.ApplicationName = v
}

// GetPlayerCount returns the PlayerCount field value
func (o *CCUApplicationTelemetry) GetPlayerCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlayerCount
}

// GetPlayerCountOk returns a tuple with the PlayerCount field value
// and a boolean to check if the value has been set.
func (o *CCUApplicationTelemetry) GetPlayerCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerCount, true
}

// SetPlayerCount sets field value
func (o *CCUApplicationTelemetry) SetPlayerCount(v int32) {
	o.PlayerCount = v
}

// GetMaxPlayers returns the MaxPlayers field value
func (o *CCUApplicationTelemetry) GetMaxPlayers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxPlayers
}

// GetMaxPlayersOk returns a tuple with the MaxPlayers field value
// and a boolean to check if the value has been set.
func (o *CCUApplicationTelemetry) GetMaxPlayersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxPlayers, true
}

// SetMaxPlayers sets field value
func (o *CCUApplicationTelemetry) SetMaxPlayers(v int32) {
	o.MaxPlayers = v
}

func (o CCUApplicationTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CCUApplicationTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["applicationName"] = o.ApplicationName
	toSerialize["playerCount"] = o.PlayerCount
	toSerialize["maxPlayers"] = o.MaxPlayers
	return toSerialize, nil
}

func (o *CCUApplicationTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"applicationId",
		"applicationName",
		"playerCount",
		"maxPlayers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCCUApplicationTelemetry := _CCUApplicationTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCCUApplicationTelemetry)

	if err != nil {
		return err
	}

	*o = CCUApplicationTelemetry(varCCUApplicationTelemetry)

	return err
}

type NullableCCUApplicationTelemetry struct {
	value *CCUApplicationTelemetry
	isSet bool
}

func (v NullableCCUApplicationTelemetry) Get() *CCUApplicationTelemetry {
	return v.value
}

func (v *NullableCCUApplicationTelemetry) Set(val *CCUApplicationTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableCCUApplicationTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableCCUApplicationTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCCUApplicationTelemetry(val *CCUApplicationTelemetry) *NullableCCUApplicationTelemetry {
	return &NullableCCUApplicationTelemetry{value: val, isSet: true}
}

func (v NullableCCUApplicationTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCCUApplicationTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
