/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PatchJobReportDeploymentRegion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchJobReportDeploymentRegion{}

// PatchJobReportDeploymentRegion struct for PatchJobReportDeploymentRegion
type PatchJobReportDeploymentRegion struct {
	// The Deployment Region's details
	DeploymentRegion GenericModel `json:"deploymentRegion"`
	// Progress for just this Deployment Region
	Progress NullablePatchJobReportProgress `json:"progress"`
	// Patch job report data based on DC location
	DcLocationData []PatchJobReportDcLocation `json:"dcLocationData"`
}

type _PatchJobReportDeploymentRegion PatchJobReportDeploymentRegion

// NewPatchJobReportDeploymentRegion instantiates a new PatchJobReportDeploymentRegion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchJobReportDeploymentRegion(deploymentRegion GenericModel, progress NullablePatchJobReportProgress, dcLocationData []PatchJobReportDcLocation) *PatchJobReportDeploymentRegion {
	this := PatchJobReportDeploymentRegion{}
	this.DeploymentRegion = deploymentRegion
	this.Progress = progress
	this.DcLocationData = dcLocationData
	return &this
}

// NewPatchJobReportDeploymentRegionWithDefaults instantiates a new PatchJobReportDeploymentRegion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchJobReportDeploymentRegionWithDefaults() *PatchJobReportDeploymentRegion {
	this := PatchJobReportDeploymentRegion{}
	return &this
}

// GetDeploymentRegion returns the DeploymentRegion field value
func (o *PatchJobReportDeploymentRegion) GetDeploymentRegion() GenericModel {
	if o == nil {
		var ret GenericModel
		return ret
	}

	return o.DeploymentRegion
}

// GetDeploymentRegionOk returns a tuple with the DeploymentRegion field value
// and a boolean to check if the value has been set.
func (o *PatchJobReportDeploymentRegion) GetDeploymentRegionOk() (*GenericModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentRegion, true
}

// SetDeploymentRegion sets field value
func (o *PatchJobReportDeploymentRegion) SetDeploymentRegion(v GenericModel) {
	o.DeploymentRegion = v
}

// GetProgress returns the Progress field value
// If the value is explicit nil, the zero value for PatchJobReportProgress will be returned
func (o *PatchJobReportDeploymentRegion) GetProgress() PatchJobReportProgress {
	if o == nil || o.Progress.Get() == nil {
		var ret PatchJobReportProgress
		return ret
	}

	return *o.Progress.Get()
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchJobReportDeploymentRegion) GetProgressOk() (*PatchJobReportProgress, bool) {
	if o == nil {
		return nil, false
	}
	return o.Progress.Get(), o.Progress.IsSet()
}

// SetProgress sets field value
func (o *PatchJobReportDeploymentRegion) SetProgress(v PatchJobReportProgress) {
	o.Progress.Set(&v)
}

// GetDcLocationData returns the DcLocationData field value
func (o *PatchJobReportDeploymentRegion) GetDcLocationData() []PatchJobReportDcLocation {
	if o == nil {
		var ret []PatchJobReportDcLocation
		return ret
	}

	return o.DcLocationData
}

// GetDcLocationDataOk returns a tuple with the DcLocationData field value
// and a boolean to check if the value has been set.
func (o *PatchJobReportDeploymentRegion) GetDcLocationDataOk() ([]PatchJobReportDcLocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.DcLocationData, true
}

// SetDcLocationData sets field value
func (o *PatchJobReportDeploymentRegion) SetDcLocationData(v []PatchJobReportDcLocation) {
	o.DcLocationData = v
}

func (o PatchJobReportDeploymentRegion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchJobReportDeploymentRegion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deploymentRegion"] = o.DeploymentRegion
	toSerialize["progress"] = o.Progress.Get()
	toSerialize["dcLocationData"] = o.DcLocationData
	return toSerialize, nil
}

func (o *PatchJobReportDeploymentRegion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deploymentRegion",
		"progress",
		"dcLocationData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchJobReportDeploymentRegion := _PatchJobReportDeploymentRegion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchJobReportDeploymentRegion)

	if err != nil {
		return err
	}

	*o = PatchJobReportDeploymentRegion(varPatchJobReportDeploymentRegion)

	return err
}

type NullablePatchJobReportDeploymentRegion struct {
	value *PatchJobReportDeploymentRegion
	isSet bool
}

func (v NullablePatchJobReportDeploymentRegion) Get() *PatchJobReportDeploymentRegion {
	return v.value
}

func (v *NullablePatchJobReportDeploymentRegion) Set(val *PatchJobReportDeploymentRegion) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchJobReportDeploymentRegion) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchJobReportDeploymentRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchJobReportDeploymentRegion(val *PatchJobReportDeploymentRegion) *NullablePatchJobReportDeploymentRegion {
	return &NullablePatchJobReportDeploymentRegion{value: val, isSet: true}
}

func (v NullablePatchJobReportDeploymentRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchJobReportDeploymentRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
