/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeploymentContainerLocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeploymentContainerLocation{}

// DeploymentContainerLocation struct for DeploymentContainerLocation
type DeploymentContainerLocation struct {
	// This deploymentContainerLocation's ID
	Id string `json:"id"`
	// The cloud provider ID of this location. For a list of cloud providers see [`GET /v3/cloud/provider`](#/Cloud/get_v3_cloud_provider)
	CloudProviderId int32 `json:"cloudProviderId"`
	// The ID of the data center. Find all possible values from [`GET /v3/cloud/dcLocation`](#/Cloud/get_v3_cloud_dcLocation)
	DcLocationId int32 `json:"dcLocationId"`
	// The primary instance type to use. Find all possible values from [`GET /v3/cloud/instanceType`](#/Cloud/get_v3_cloud_instanceType)
	PrimaryInstanceTypeName NullableString `json:"primaryInstanceTypeName"`
	// It will show either primary instance type is available or not
	PrimaryInstanceTypeStatus int32 `json:"primaryInstanceTypeStatus"`
	// The secondary instance type to use. Find all possible values from [`GET /v3/cloud/instanceType`](#/Cloud/get_v3_cloud_instanceType)
	SecondaryInstanceTypeName NullableString `json:"secondaryInstanceTypeName,omitempty"`
	// It will show either secondary instance type is available or not
	SecondaryInstanceTypeStatus int32 `json:"secondaryInstanceTypeStatus"`
	// The CPU platform to use for the given `cloudProviderId`. Find all possible values from [`GET /v3/cloud/cpuPlatform`](#/Cloud/get_v3_cloud_cpuPlatform). Null value means that a CPU platform is chosen automatically by the cloud provider. Note that this selector is not available on all cloud platforms
	// Deprecated
	CpuPlatform NullableString `json:"cpuPlatform,omitempty"`
	// If set to 1, all application instances will be gracefully removed in this cloud location. After all application instances are removed this object will also be deleted
	MarkedForDeletion int32 `json:"markedForDeletion"`
}

type _DeploymentContainerLocation DeploymentContainerLocation

// NewDeploymentContainerLocation instantiates a new DeploymentContainerLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeploymentContainerLocation(id string, cloudProviderId int32, dcLocationId int32, primaryInstanceTypeName NullableString, primaryInstanceTypeStatus int32, secondaryInstanceTypeStatus int32, markedForDeletion int32) *DeploymentContainerLocation {
	this := DeploymentContainerLocation{}
	this.Id = id
	this.CloudProviderId = cloudProviderId
	this.DcLocationId = dcLocationId
	this.PrimaryInstanceTypeName = primaryInstanceTypeName
	this.PrimaryInstanceTypeStatus = primaryInstanceTypeStatus
	this.SecondaryInstanceTypeStatus = secondaryInstanceTypeStatus
	this.MarkedForDeletion = markedForDeletion
	return &this
}

// NewDeploymentContainerLocationWithDefaults instantiates a new DeploymentContainerLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeploymentContainerLocationWithDefaults() *DeploymentContainerLocation {
	this := DeploymentContainerLocation{}
	return &this
}

// GetId returns the Id field value
func (o *DeploymentContainerLocation) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeploymentContainerLocation) SetId(v string) {
	o.Id = v
}

// GetCloudProviderId returns the CloudProviderId field value
func (o *DeploymentContainerLocation) GetCloudProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CloudProviderId
}

// GetCloudProviderIdOk returns a tuple with the CloudProviderId field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetCloudProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProviderId, true
}

// SetCloudProviderId sets field value
func (o *DeploymentContainerLocation) SetCloudProviderId(v int32) {
	o.CloudProviderId = v
}

// GetDcLocationId returns the DcLocationId field value
func (o *DeploymentContainerLocation) GetDcLocationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DcLocationId
}

// GetDcLocationIdOk returns a tuple with the DcLocationId field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetDcLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DcLocationId, true
}

// SetDcLocationId sets field value
func (o *DeploymentContainerLocation) SetDcLocationId(v int32) {
	o.DcLocationId = v
}

// GetPrimaryInstanceTypeName returns the PrimaryInstanceTypeName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *DeploymentContainerLocation) GetPrimaryInstanceTypeName() string {
	if o == nil || o.PrimaryInstanceTypeName.Get() == nil {
		var ret string
		return ret
	}

	return *o.PrimaryInstanceTypeName.Get()
}

// GetPrimaryInstanceTypeNameOk returns a tuple with the PrimaryInstanceTypeName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentContainerLocation) GetPrimaryInstanceTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrimaryInstanceTypeName.Get(), o.PrimaryInstanceTypeName.IsSet()
}

// SetPrimaryInstanceTypeName sets field value
func (o *DeploymentContainerLocation) SetPrimaryInstanceTypeName(v string) {
	o.PrimaryInstanceTypeName.Set(&v)
}

// GetPrimaryInstanceTypeStatus returns the PrimaryInstanceTypeStatus field value
func (o *DeploymentContainerLocation) GetPrimaryInstanceTypeStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PrimaryInstanceTypeStatus
}

// GetPrimaryInstanceTypeStatusOk returns a tuple with the PrimaryInstanceTypeStatus field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetPrimaryInstanceTypeStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryInstanceTypeStatus, true
}

// SetPrimaryInstanceTypeStatus sets field value
func (o *DeploymentContainerLocation) SetPrimaryInstanceTypeStatus(v int32) {
	o.PrimaryInstanceTypeStatus = v
}

// GetSecondaryInstanceTypeName returns the SecondaryInstanceTypeName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeploymentContainerLocation) GetSecondaryInstanceTypeName() string {
	if o == nil || IsNil(o.SecondaryInstanceTypeName.Get()) {
		var ret string
		return ret
	}
	return *o.SecondaryInstanceTypeName.Get()
}

// GetSecondaryInstanceTypeNameOk returns a tuple with the SecondaryInstanceTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeploymentContainerLocation) GetSecondaryInstanceTypeNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecondaryInstanceTypeName.Get(), o.SecondaryInstanceTypeName.IsSet()
}

// HasSecondaryInstanceTypeName returns a boolean if a field has been set.
func (o *DeploymentContainerLocation) HasSecondaryInstanceTypeName() bool {
	if o != nil && o.SecondaryInstanceTypeName.IsSet() {
		return true
	}

	return false
}

// SetSecondaryInstanceTypeName gets a reference to the given NullableString and assigns it to the SecondaryInstanceTypeName field.
func (o *DeploymentContainerLocation) SetSecondaryInstanceTypeName(v string) {
	o.SecondaryInstanceTypeName.Set(&v)
}

// SetSecondaryInstanceTypeNameNil sets the value for SecondaryInstanceTypeName to be an explicit nil
func (o *DeploymentContainerLocation) SetSecondaryInstanceTypeNameNil() {
	o.SecondaryInstanceTypeName.Set(nil)
}

// UnsetSecondaryInstanceTypeName ensures that no value is present for SecondaryInstanceTypeName, not even an explicit nil
func (o *DeploymentContainerLocation) UnsetSecondaryInstanceTypeName() {
	o.SecondaryInstanceTypeName.Unset()
}

// GetSecondaryInstanceTypeStatus returns the SecondaryInstanceTypeStatus field value
func (o *DeploymentContainerLocation) GetSecondaryInstanceTypeStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SecondaryInstanceTypeStatus
}

// GetSecondaryInstanceTypeStatusOk returns a tuple with the SecondaryInstanceTypeStatus field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetSecondaryInstanceTypeStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecondaryInstanceTypeStatus, true
}

// SetSecondaryInstanceTypeStatus sets field value
func (o *DeploymentContainerLocation) SetSecondaryInstanceTypeStatus(v int32) {
	o.SecondaryInstanceTypeStatus = v
}

// GetCpuPlatform returns the CpuPlatform field value if set, zero value otherwise (both if not set or set to explicit null).
// Deprecated
func (o *DeploymentContainerLocation) GetCpuPlatform() string {
	if o == nil || IsNil(o.CpuPlatform.Get()) {
		var ret string
		return ret
	}
	return *o.CpuPlatform.Get()
}

// GetCpuPlatformOk returns a tuple with the CpuPlatform field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
// Deprecated
func (o *DeploymentContainerLocation) GetCpuPlatformOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuPlatform.Get(), o.CpuPlatform.IsSet()
}

// HasCpuPlatform returns a boolean if a field has been set.
func (o *DeploymentContainerLocation) HasCpuPlatform() bool {
	if o != nil && o.CpuPlatform.IsSet() {
		return true
	}

	return false
}

// SetCpuPlatform gets a reference to the given NullableString and assigns it to the CpuPlatform field.
// Deprecated
func (o *DeploymentContainerLocation) SetCpuPlatform(v string) {
	o.CpuPlatform.Set(&v)
}

// SetCpuPlatformNil sets the value for CpuPlatform to be an explicit nil
func (o *DeploymentContainerLocation) SetCpuPlatformNil() {
	o.CpuPlatform.Set(nil)
}

// UnsetCpuPlatform ensures that no value is present for CpuPlatform, not even an explicit nil
func (o *DeploymentContainerLocation) UnsetCpuPlatform() {
	o.CpuPlatform.Unset()
}

// GetMarkedForDeletion returns the MarkedForDeletion field value
func (o *DeploymentContainerLocation) GetMarkedForDeletion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MarkedForDeletion
}

// GetMarkedForDeletionOk returns a tuple with the MarkedForDeletion field value
// and a boolean to check if the value has been set.
func (o *DeploymentContainerLocation) GetMarkedForDeletionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarkedForDeletion, true
}

// SetMarkedForDeletion sets field value
func (o *DeploymentContainerLocation) SetMarkedForDeletion(v int32) {
	o.MarkedForDeletion = v
}

func (o DeploymentContainerLocation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeploymentContainerLocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["cloudProviderId"] = o.CloudProviderId
	toSerialize["dcLocationId"] = o.DcLocationId
	toSerialize["primaryInstanceTypeName"] = o.PrimaryInstanceTypeName.Get()
	toSerialize["primaryInstanceTypeStatus"] = o.PrimaryInstanceTypeStatus
	if o.SecondaryInstanceTypeName.IsSet() {
		toSerialize["secondaryInstanceTypeName"] = o.SecondaryInstanceTypeName.Get()
	}
	toSerialize["secondaryInstanceTypeStatus"] = o.SecondaryInstanceTypeStatus
	if o.CpuPlatform.IsSet() {
		toSerialize["cpuPlatform"] = o.CpuPlatform.Get()
	}
	toSerialize["markedForDeletion"] = o.MarkedForDeletion
	return toSerialize, nil
}

func (o *DeploymentContainerLocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"cloudProviderId",
		"dcLocationId",
		"primaryInstanceTypeName",
		"primaryInstanceTypeStatus",
		"secondaryInstanceTypeStatus",
		"markedForDeletion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeploymentContainerLocation := _DeploymentContainerLocation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeploymentContainerLocation)

	if err != nil {
		return err
	}

	*o = DeploymentContainerLocation(varDeploymentContainerLocation)

	return err
}

type NullableDeploymentContainerLocation struct {
	value *DeploymentContainerLocation
	isSet bool
}

func (v NullableDeploymentContainerLocation) Get() *DeploymentContainerLocation {
	return v.value
}

func (v *NullableDeploymentContainerLocation) Set(val *DeploymentContainerLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableDeploymentContainerLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableDeploymentContainerLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeploymentContainerLocation(val *DeploymentContainerLocation) *NullableDeploymentContainerLocation {
	return &NullableDeploymentContainerLocation{value: val, isSet: true}
}

func (v NullableDeploymentContainerLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeploymentContainerLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
