/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostHardwareCapacityDataTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostHardwareCapacityDataTelemetry{}

// HostHardwareCapacityDataTelemetry struct for HostHardwareCapacityDataTelemetry
type HostHardwareCapacityDataTelemetry struct {
	// The time at which the last update occurred
	Timestamp int32 `json:"timestamp"`
	// The value of data at this timestamp
	Value HostHardwareCapacityDataValueTelemetry `json:"value"`
}

type _HostHardwareCapacityDataTelemetry HostHardwareCapacityDataTelemetry

// NewHostHardwareCapacityDataTelemetry instantiates a new HostHardwareCapacityDataTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostHardwareCapacityDataTelemetry(timestamp int32, value HostHardwareCapacityDataValueTelemetry) *HostHardwareCapacityDataTelemetry {
	this := HostHardwareCapacityDataTelemetry{}
	this.Timestamp = timestamp
	this.Value = value
	return &this
}

// NewHostHardwareCapacityDataTelemetryWithDefaults instantiates a new HostHardwareCapacityDataTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostHardwareCapacityDataTelemetryWithDefaults() *HostHardwareCapacityDataTelemetry {
	this := HostHardwareCapacityDataTelemetry{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *HostHardwareCapacityDataTelemetry) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HostHardwareCapacityDataTelemetry) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HostHardwareCapacityDataTelemetry) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetValue returns the Value field value
func (o *HostHardwareCapacityDataTelemetry) GetValue() HostHardwareCapacityDataValueTelemetry {
	if o == nil {
		var ret HostHardwareCapacityDataValueTelemetry
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *HostHardwareCapacityDataTelemetry) GetValueOk() (*HostHardwareCapacityDataValueTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *HostHardwareCapacityDataTelemetry) SetValue(v HostHardwareCapacityDataValueTelemetry) {
	o.Value = v
}

func (o HostHardwareCapacityDataTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostHardwareCapacityDataTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *HostHardwareCapacityDataTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostHardwareCapacityDataTelemetry := _HostHardwareCapacityDataTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostHardwareCapacityDataTelemetry)

	if err != nil {
		return err
	}

	*o = HostHardwareCapacityDataTelemetry(varHostHardwareCapacityDataTelemetry)

	return err
}

type NullableHostHardwareCapacityDataTelemetry struct {
	value *HostHardwareCapacityDataTelemetry
	isSet bool
}

func (v NullableHostHardwareCapacityDataTelemetry) Get() *HostHardwareCapacityDataTelemetry {
	return v.value
}

func (v *NullableHostHardwareCapacityDataTelemetry) Set(val *HostHardwareCapacityDataTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableHostHardwareCapacityDataTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableHostHardwareCapacityDataTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostHardwareCapacityDataTelemetry(val *HostHardwareCapacityDataTelemetry) *NullableHostHardwareCapacityDataTelemetry {
	return &NullableHostHardwareCapacityDataTelemetry{value: val, isSet: true}
}

func (v NullableHostHardwareCapacityDataTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostHardwareCapacityDataTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
