/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostCapacityTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostCapacityTemplate{}

// HostCapacityTemplate struct for HostCapacityTemplate
type HostCapacityTemplate struct {
	// The ID of the Host Capacity Template
	Id string `json:"id"`
	// IDs of the Fleets that use this Host Capacity Template
	FleetIds []string `json:"fleetIds"`
	// IDs of the Application Builds that use this Host Capacity Template
	ApplicationBuildIds []string `json:"applicationBuildIds"`
	// The public name of your Host Capacity Template
	Name string `json:"name"`
	// 1 if the Host Capacity Template is in use by a Fleet or Application Build, 0 if it is not.
	InUse int32 `json:"inUse"`
	// The Unix timestamp at which this element is created
	CreatedAt int32 `json:"createdAt"`
}

type _HostCapacityTemplate HostCapacityTemplate

// NewHostCapacityTemplate instantiates a new HostCapacityTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostCapacityTemplate(id string, fleetIds []string, applicationBuildIds []string, name string, inUse int32, createdAt int32) *HostCapacityTemplate {
	this := HostCapacityTemplate{}
	this.Id = id
	this.FleetIds = fleetIds
	this.ApplicationBuildIds = applicationBuildIds
	this.Name = name
	this.InUse = inUse
	this.CreatedAt = createdAt
	return &this
}

// NewHostCapacityTemplateWithDefaults instantiates a new HostCapacityTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostCapacityTemplateWithDefaults() *HostCapacityTemplate {
	this := HostCapacityTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *HostCapacityTemplate) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *HostCapacityTemplate) SetId(v string) {
	o.Id = v
}

// GetFleetIds returns the FleetIds field value
func (o *HostCapacityTemplate) GetFleetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FleetIds
}

// GetFleetIdsOk returns a tuple with the FleetIds field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetFleetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FleetIds, true
}

// SetFleetIds sets field value
func (o *HostCapacityTemplate) SetFleetIds(v []string) {
	o.FleetIds = v
}

// GetApplicationBuildIds returns the ApplicationBuildIds field value
func (o *HostCapacityTemplate) GetApplicationBuildIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApplicationBuildIds
}

// GetApplicationBuildIdsOk returns a tuple with the ApplicationBuildIds field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetApplicationBuildIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationBuildIds, true
}

// SetApplicationBuildIds sets field value
func (o *HostCapacityTemplate) SetApplicationBuildIds(v []string) {
	o.ApplicationBuildIds = v
}

// GetName returns the Name field value
func (o *HostCapacityTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HostCapacityTemplate) SetName(v string) {
	o.Name = v
}

// GetInUse returns the InUse field value
func (o *HostCapacityTemplate) GetInUse() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InUse
}

// GetInUseOk returns a tuple with the InUse field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetInUseOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InUse, true
}

// SetInUse sets field value
func (o *HostCapacityTemplate) SetInUse(v int32) {
	o.InUse = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *HostCapacityTemplate) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *HostCapacityTemplate) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *HostCapacityTemplate) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

func (o HostCapacityTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostCapacityTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["fleetIds"] = o.FleetIds
	toSerialize["applicationBuildIds"] = o.ApplicationBuildIds
	toSerialize["name"] = o.Name
	toSerialize["inUse"] = o.InUse
	toSerialize["createdAt"] = o.CreatedAt
	return toSerialize, nil
}

func (o *HostCapacityTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"fleetIds",
		"applicationBuildIds",
		"name",
		"inUse",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostCapacityTemplate := _HostCapacityTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostCapacityTemplate)

	if err != nil {
		return err
	}

	*o = HostCapacityTemplate(varHostCapacityTemplate)

	return err
}

type NullableHostCapacityTemplate struct {
	value *HostCapacityTemplate
	isSet bool
}

func (v NullableHostCapacityTemplate) Get() *HostCapacityTemplate {
	return v.value
}

func (v *NullableHostCapacityTemplate) Set(val *HostCapacityTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableHostCapacityTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableHostCapacityTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostCapacityTemplate(val *HostCapacityTemplate) *NullableHostCapacityTemplate {
	return &NullableHostCapacityTemplate{value: val, isSet: true}
}

func (v NullableHostCapacityTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostCapacityTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
