/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostUplink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostUplink{}

// HostUplink struct for HostUplink
type HostUplink struct {
	// The cacti ID of the uplink
	UplinkId int32 `json:"uplinkId"`
	// True if the uplink is an aggregated uplink, false if it is not aggregated
	Aggregate bool `json:"aggregate"`
}

type _HostUplink HostUplink

// NewHostUplink instantiates a new HostUplink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostUplink(uplinkId int32, aggregate bool) *HostUplink {
	this := HostUplink{}
	this.UplinkId = uplinkId
	this.Aggregate = aggregate
	return &this
}

// NewHostUplinkWithDefaults instantiates a new HostUplink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostUplinkWithDefaults() *HostUplink {
	this := HostUplink{}
	return &this
}

// GetUplinkId returns the UplinkId field value
func (o *HostUplink) GetUplinkId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UplinkId
}

// GetUplinkIdOk returns a tuple with the UplinkId field value
// and a boolean to check if the value has been set.
func (o *HostUplink) GetUplinkIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplinkId, true
}

// SetUplinkId sets field value
func (o *HostUplink) SetUplinkId(v int32) {
	o.UplinkId = v
}

// GetAggregate returns the Aggregate field value
func (o *HostUplink) GetAggregate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Aggregate
}

// GetAggregateOk returns a tuple with the Aggregate field value
// and a boolean to check if the value has been set.
func (o *HostUplink) GetAggregateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregate, true
}

// SetAggregate sets field value
func (o *HostUplink) SetAggregate(v bool) {
	o.Aggregate = v
}

func (o HostUplink) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostUplink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uplinkId"] = o.UplinkId
	toSerialize["aggregate"] = o.Aggregate
	return toSerialize, nil
}

func (o *HostUplink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uplinkId",
		"aggregate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostUplink := _HostUplink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostUplink)

	if err != nil {
		return err
	}

	*o = HostUplink(varHostUplink)

	return err
}

type NullableHostUplink struct {
	value *HostUplink
	isSet bool
}

func (v NullableHostUplink) Get() *HostUplink {
	return v.value
}

func (v *NullableHostUplink) Set(val *HostUplink) {
	v.value = val
	v.isSet = true
}

func (v NullableHostUplink) IsSet() bool {
	return v.isSet
}

func (v *NullableHostUplink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostUplink(val *HostUplink) *NullableHostUplink {
	return &NullableHostUplink{value: val, isSet: true}
}

func (v NullableHostUplink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostUplink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
