/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceProperty{}

// ApplicationInstanceProperty struct for ApplicationInstanceProperty
type ApplicationInstanceProperty struct {
	// The application instance property ID
	Id string `json:"id"`
	// The application instance property type. For a list of application property types see [`GET /v3/application/property/type`](#/Application/get_v3_application_property_type)
	PropertyType int32 `json:"propertyType"`
	// The application instance property key. Only hyphens (-), underscores (_), lowercase characters and numbers are allowed. Keys must start with a lowercase character
	PropertyKey string `json:"propertyKey"`
	// The application instance property value
	PropertyValue string `json:"propertyValue"`
}

type _ApplicationInstanceProperty ApplicationInstanceProperty

// NewApplicationInstanceProperty instantiates a new ApplicationInstanceProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceProperty(id string, propertyType int32, propertyKey string, propertyValue string) *ApplicationInstanceProperty {
	this := ApplicationInstanceProperty{}
	this.Id = id
	this.PropertyType = propertyType
	this.PropertyKey = propertyKey
	this.PropertyValue = propertyValue
	return &this
}

// NewApplicationInstancePropertyWithDefaults instantiates a new ApplicationInstanceProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstancePropertyWithDefaults() *ApplicationInstanceProperty {
	this := ApplicationInstanceProperty{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationInstanceProperty) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceProperty) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationInstanceProperty) SetId(v string) {
	o.Id = v
}

// GetPropertyType returns the PropertyType field value
func (o *ApplicationInstanceProperty) GetPropertyType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PropertyType
}

// GetPropertyTypeOk returns a tuple with the PropertyType field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceProperty) GetPropertyTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyType, true
}

// SetPropertyType sets field value
func (o *ApplicationInstanceProperty) SetPropertyType(v int32) {
	o.PropertyType = v
}

// GetPropertyKey returns the PropertyKey field value
func (o *ApplicationInstanceProperty) GetPropertyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyKey
}

// GetPropertyKeyOk returns a tuple with the PropertyKey field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceProperty) GetPropertyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyKey, true
}

// SetPropertyKey sets field value
func (o *ApplicationInstanceProperty) SetPropertyKey(v string) {
	o.PropertyKey = v
}

// GetPropertyValue returns the PropertyValue field value
func (o *ApplicationInstanceProperty) GetPropertyValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyValue
}

// GetPropertyValueOk returns a tuple with the PropertyValue field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceProperty) GetPropertyValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyValue, true
}

// SetPropertyValue sets field value
func (o *ApplicationInstanceProperty) SetPropertyValue(v string) {
	o.PropertyValue = v
}

func (o ApplicationInstanceProperty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["propertyType"] = o.PropertyType
	toSerialize["propertyKey"] = o.PropertyKey
	toSerialize["propertyValue"] = o.PropertyValue
	return toSerialize, nil
}

func (o *ApplicationInstanceProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"propertyType",
		"propertyKey",
		"propertyValue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceProperty := _ApplicationInstanceProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceProperty)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceProperty(varApplicationInstanceProperty)

	return err
}

type NullableApplicationInstanceProperty struct {
	value *ApplicationInstanceProperty
	isSet bool
}

func (v NullableApplicationInstanceProperty) Get() *ApplicationInstanceProperty {
	return v.value
}

func (v *NullableApplicationInstanceProperty) Set(val *ApplicationInstanceProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceProperty(val *ApplicationInstanceProperty) *NullableApplicationInstanceProperty {
	return &NullableApplicationInstanceProperty{value: val, isSet: true}
}

func (v NullableApplicationInstanceProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
