/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApplicationInstanceStopMethod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceStopMethod{}

// ApplicationInstanceStopMethod struct for ApplicationInstanceStopMethod
type ApplicationInstanceStopMethod struct {
	// Stop method type, list of types can be found in: [GET /v3/application/stopMethod](game-publisher#/Application/getApplicationStopMethods)
	MethodId *int32 `json:"methodId,omitempty"`
	// Stop method timeout in seconds, default value is 1800 seconds.
	Timeout *int32 `json:"timeout,omitempty"`
}

// NewApplicationInstanceStopMethod instantiates a new ApplicationInstanceStopMethod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceStopMethod() *ApplicationInstanceStopMethod {
	this := ApplicationInstanceStopMethod{}
	return &this
}

// NewApplicationInstanceStopMethodWithDefaults instantiates a new ApplicationInstanceStopMethod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceStopMethodWithDefaults() *ApplicationInstanceStopMethod {
	this := ApplicationInstanceStopMethod{}
	return &this
}

// GetMethodId returns the MethodId field value if set, zero value otherwise.
func (o *ApplicationInstanceStopMethod) GetMethodId() int32 {
	if o == nil || IsNil(o.MethodId) {
		var ret int32
		return ret
	}
	return *o.MethodId
}

// GetMethodIdOk returns a tuple with the MethodId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStopMethod) GetMethodIdOk() (*int32, bool) {
	if o == nil || IsNil(o.MethodId) {
		return nil, false
	}
	return o.MethodId, true
}

// HasMethodId returns a boolean if a field has been set.
func (o *ApplicationInstanceStopMethod) HasMethodId() bool {
	if o != nil && !IsNil(o.MethodId) {
		return true
	}

	return false
}

// SetMethodId gets a reference to the given int32 and assigns it to the MethodId field.
func (o *ApplicationInstanceStopMethod) SetMethodId(v int32) {
	o.MethodId = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *ApplicationInstanceStopMethod) GetTimeout() int32 {
	if o == nil || IsNil(o.Timeout) {
		var ret int32
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStopMethod) GetTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *ApplicationInstanceStopMethod) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given int32 and assigns it to the Timeout field.
func (o *ApplicationInstanceStopMethod) SetTimeout(v int32) {
	o.Timeout = &v
}

func (o ApplicationInstanceStopMethod) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceStopMethod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MethodId) {
		toSerialize["methodId"] = o.MethodId
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	return toSerialize, nil
}

type NullableApplicationInstanceStopMethod struct {
	value *ApplicationInstanceStopMethod
	isSet bool
}

func (v NullableApplicationInstanceStopMethod) Get() *ApplicationInstanceStopMethod {
	return v.value
}

func (v *NullableApplicationInstanceStopMethod) Set(val *ApplicationInstanceStopMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceStopMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceStopMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceStopMethod(val *ApplicationInstanceStopMethod) *NullableApplicationInstanceStopMethod {
	return &NullableApplicationInstanceStopMethod{value: val, isSet: true}
}

func (v NullableApplicationInstanceStopMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceStopMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
