/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DcLocationVicinityMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DcLocationVicinityMapping{}

// DcLocationVicinityMapping struct for DcLocationVicinityMapping
type DcLocationVicinityMapping struct {
	// An i3D.net dcLocationId
	I3dDcLocationId int32 `json:"i3dDcLocationId"`
	// A cloud dcLocationId
	CloudDcLocationId int32 `json:"cloudDcLocationId"`
}

type _DcLocationVicinityMapping DcLocationVicinityMapping

// NewDcLocationVicinityMapping instantiates a new DcLocationVicinityMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDcLocationVicinityMapping(i3dDcLocationId int32, cloudDcLocationId int32) *DcLocationVicinityMapping {
	this := DcLocationVicinityMapping{}
	this.I3dDcLocationId = i3dDcLocationId
	this.CloudDcLocationId = cloudDcLocationId
	return &this
}

// NewDcLocationVicinityMappingWithDefaults instantiates a new DcLocationVicinityMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDcLocationVicinityMappingWithDefaults() *DcLocationVicinityMapping {
	this := DcLocationVicinityMapping{}
	return &this
}

// GetI3dDcLocationId returns the I3dDcLocationId field value
func (o *DcLocationVicinityMapping) GetI3dDcLocationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.I3dDcLocationId
}

// GetI3dDcLocationIdOk returns a tuple with the I3dDcLocationId field value
// and a boolean to check if the value has been set.
func (o *DcLocationVicinityMapping) GetI3dDcLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.I3dDcLocationId, true
}

// SetI3dDcLocationId sets field value
func (o *DcLocationVicinityMapping) SetI3dDcLocationId(v int32) {
	o.I3dDcLocationId = v
}

// GetCloudDcLocationId returns the CloudDcLocationId field value
func (o *DcLocationVicinityMapping) GetCloudDcLocationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CloudDcLocationId
}

// GetCloudDcLocationIdOk returns a tuple with the CloudDcLocationId field value
// and a boolean to check if the value has been set.
func (o *DcLocationVicinityMapping) GetCloudDcLocationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudDcLocationId, true
}

// SetCloudDcLocationId sets field value
func (o *DcLocationVicinityMapping) SetCloudDcLocationId(v int32) {
	o.CloudDcLocationId = v
}

func (o DcLocationVicinityMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DcLocationVicinityMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["i3dDcLocationId"] = o.I3dDcLocationId
	toSerialize["cloudDcLocationId"] = o.CloudDcLocationId
	return toSerialize, nil
}

func (o *DcLocationVicinityMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"i3dDcLocationId",
		"cloudDcLocationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDcLocationVicinityMapping := _DcLocationVicinityMapping{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDcLocationVicinityMapping)

	if err != nil {
		return err
	}

	*o = DcLocationVicinityMapping(varDcLocationVicinityMapping)

	return err
}

type NullableDcLocationVicinityMapping struct {
	value *DcLocationVicinityMapping
	isSet bool
}

func (v NullableDcLocationVicinityMapping) Get() *DcLocationVicinityMapping {
	return v.value
}

func (v *NullableDcLocationVicinityMapping) Set(val *DcLocationVicinityMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableDcLocationVicinityMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableDcLocationVicinityMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDcLocationVicinityMapping(val *DcLocationVicinityMapping) *NullableDcLocationVicinityMapping {
	return &NullableDcLocationVicinityMapping{value: val, isSet: true}
}

func (v NullableDcLocationVicinityMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDcLocationVicinityMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
