/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BulkReserveHostByFleetStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkReserveHostByFleetStatus{}

// BulkReserveHostByFleetStatus struct for BulkReserveHostByFleetStatus
type BulkReserveHostByFleetStatus struct {
	// Fleet ID that was assigned to the host prior to bulk reservation.
	OldFleetId string `json:"oldFleetId"`
	// Fleet ID that will be assigned to the host after completion of bulk reservation.
	NewFleetId string `json:"newFleetId"`
	// ID of the host.
	HostId int32 `json:"hostId"`
	// When the value is 1 then the host is not changed to the new fleet ID, when value is 0 than the host is changed to the new fleet ID.
	InProgress int32 `json:"inProgress"`
}

type _BulkReserveHostByFleetStatus BulkReserveHostByFleetStatus

// NewBulkReserveHostByFleetStatus instantiates a new BulkReserveHostByFleetStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkReserveHostByFleetStatus(oldFleetId string, newFleetId string, hostId int32, inProgress int32) *BulkReserveHostByFleetStatus {
	this := BulkReserveHostByFleetStatus{}
	this.OldFleetId = oldFleetId
	this.NewFleetId = newFleetId
	this.HostId = hostId
	this.InProgress = inProgress
	return &this
}

// NewBulkReserveHostByFleetStatusWithDefaults instantiates a new BulkReserveHostByFleetStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkReserveHostByFleetStatusWithDefaults() *BulkReserveHostByFleetStatus {
	this := BulkReserveHostByFleetStatus{}
	return &this
}

// GetOldFleetId returns the OldFleetId field value
func (o *BulkReserveHostByFleetStatus) GetOldFleetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OldFleetId
}

// GetOldFleetIdOk returns a tuple with the OldFleetId field value
// and a boolean to check if the value has been set.
func (o *BulkReserveHostByFleetStatus) GetOldFleetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OldFleetId, true
}

// SetOldFleetId sets field value
func (o *BulkReserveHostByFleetStatus) SetOldFleetId(v string) {
	o.OldFleetId = v
}

// GetNewFleetId returns the NewFleetId field value
func (o *BulkReserveHostByFleetStatus) GetNewFleetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewFleetId
}

// GetNewFleetIdOk returns a tuple with the NewFleetId field value
// and a boolean to check if the value has been set.
func (o *BulkReserveHostByFleetStatus) GetNewFleetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewFleetId, true
}

// SetNewFleetId sets field value
func (o *BulkReserveHostByFleetStatus) SetNewFleetId(v string) {
	o.NewFleetId = v
}

// GetHostId returns the HostId field value
func (o *BulkReserveHostByFleetStatus) GetHostId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value
// and a boolean to check if the value has been set.
func (o *BulkReserveHostByFleetStatus) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostId, true
}

// SetHostId sets field value
func (o *BulkReserveHostByFleetStatus) SetHostId(v int32) {
	o.HostId = v
}

// GetInProgress returns the InProgress field value
func (o *BulkReserveHostByFleetStatus) GetInProgress() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InProgress
}

// GetInProgressOk returns a tuple with the InProgress field value
// and a boolean to check if the value has been set.
func (o *BulkReserveHostByFleetStatus) GetInProgressOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InProgress, true
}

// SetInProgress sets field value
func (o *BulkReserveHostByFleetStatus) SetInProgress(v int32) {
	o.InProgress = v
}

func (o BulkReserveHostByFleetStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkReserveHostByFleetStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["oldFleetId"] = o.OldFleetId
	toSerialize["newFleetId"] = o.NewFleetId
	toSerialize["hostId"] = o.HostId
	toSerialize["inProgress"] = o.InProgress
	return toSerialize, nil
}

func (o *BulkReserveHostByFleetStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"oldFleetId",
		"newFleetId",
		"hostId",
		"inProgress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkReserveHostByFleetStatus := _BulkReserveHostByFleetStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkReserveHostByFleetStatus)

	if err != nil {
		return err
	}

	*o = BulkReserveHostByFleetStatus(varBulkReserveHostByFleetStatus)

	return err
}

type NullableBulkReserveHostByFleetStatus struct {
	value *BulkReserveHostByFleetStatus
	isSet bool
}

func (v NullableBulkReserveHostByFleetStatus) Get() *BulkReserveHostByFleetStatus {
	return v.value
}

func (v *NullableBulkReserveHostByFleetStatus) Set(val *BulkReserveHostByFleetStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkReserveHostByFleetStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkReserveHostByFleetStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkReserveHostByFleetStatus(val *BulkReserveHostByFleetStatus) *NullableBulkReserveHostByFleetStatus {
	return &NullableBulkReserveHostByFleetStatus{value: val, isSet: true}
}

func (v NullableBulkReserveHostByFleetStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkReserveHostByFleetStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
