/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PatchJobApplicationInstancePreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchJobApplicationInstancePreview{}

// PatchJobApplicationInstancePreview struct for PatchJobApplicationInstancePreview
type PatchJobApplicationInstancePreview struct {
	// Deployment environment ID
	DeploymentEnvironmentId string `json:"deploymentEnvironmentId"`
	// Application ID
	ApplicationId string `json:"applicationId"`
	// List of fleet ID
	Fleet []string `json:"fleet"`
	// List of application build ID
	ApplicationBuild []string `json:"applicationBuild"`
}

type _PatchJobApplicationInstancePreview PatchJobApplicationInstancePreview

// NewPatchJobApplicationInstancePreview instantiates a new PatchJobApplicationInstancePreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchJobApplicationInstancePreview(deploymentEnvironmentId string, applicationId string, fleet []string, applicationBuild []string) *PatchJobApplicationInstancePreview {
	this := PatchJobApplicationInstancePreview{}
	this.DeploymentEnvironmentId = deploymentEnvironmentId
	this.ApplicationId = applicationId
	this.Fleet = fleet
	this.ApplicationBuild = applicationBuild
	return &this
}

// NewPatchJobApplicationInstancePreviewWithDefaults instantiates a new PatchJobApplicationInstancePreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchJobApplicationInstancePreviewWithDefaults() *PatchJobApplicationInstancePreview {
	this := PatchJobApplicationInstancePreview{}
	return &this
}

// GetDeploymentEnvironmentId returns the DeploymentEnvironmentId field value
func (o *PatchJobApplicationInstancePreview) GetDeploymentEnvironmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentEnvironmentId
}

// GetDeploymentEnvironmentIdOk returns a tuple with the DeploymentEnvironmentId field value
// and a boolean to check if the value has been set.
func (o *PatchJobApplicationInstancePreview) GetDeploymentEnvironmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentEnvironmentId, true
}

// SetDeploymentEnvironmentId sets field value
func (o *PatchJobApplicationInstancePreview) SetDeploymentEnvironmentId(v string) {
	o.DeploymentEnvironmentId = v
}

// GetApplicationId returns the ApplicationId field value
func (o *PatchJobApplicationInstancePreview) GetApplicationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value
// and a boolean to check if the value has been set.
func (o *PatchJobApplicationInstancePreview) GetApplicationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApplicationId, true
}

// SetApplicationId sets field value
func (o *PatchJobApplicationInstancePreview) SetApplicationId(v string) {
	o.ApplicationId = v
}

// GetFleet returns the Fleet field value
func (o *PatchJobApplicationInstancePreview) GetFleet() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fleet
}

// GetFleetOk returns a tuple with the Fleet field value
// and a boolean to check if the value has been set.
func (o *PatchJobApplicationInstancePreview) GetFleetOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fleet, true
}

// SetFleet sets field value
func (o *PatchJobApplicationInstancePreview) SetFleet(v []string) {
	o.Fleet = v
}

// GetApplicationBuild returns the ApplicationBuild field value
func (o *PatchJobApplicationInstancePreview) GetApplicationBuild() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApplicationBuild
}

// GetApplicationBuildOk returns a tuple with the ApplicationBuild field value
// and a boolean to check if the value has been set.
func (o *PatchJobApplicationInstancePreview) GetApplicationBuildOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationBuild, true
}

// SetApplicationBuild sets field value
func (o *PatchJobApplicationInstancePreview) SetApplicationBuild(v []string) {
	o.ApplicationBuild = v
}

func (o PatchJobApplicationInstancePreview) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchJobApplicationInstancePreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deploymentEnvironmentId"] = o.DeploymentEnvironmentId
	toSerialize["applicationId"] = o.ApplicationId
	toSerialize["fleet"] = o.Fleet
	toSerialize["applicationBuild"] = o.ApplicationBuild
	return toSerialize, nil
}

func (o *PatchJobApplicationInstancePreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deploymentEnvironmentId",
		"applicationId",
		"fleet",
		"applicationBuild",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchJobApplicationInstancePreview := _PatchJobApplicationInstancePreview{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPatchJobApplicationInstancePreview)

	if err != nil {
		return err
	}

	*o = PatchJobApplicationInstancePreview(varPatchJobApplicationInstancePreview)

	return err
}

type NullablePatchJobApplicationInstancePreview struct {
	value *PatchJobApplicationInstancePreview
	isSet bool
}

func (v NullablePatchJobApplicationInstancePreview) Get() *PatchJobApplicationInstancePreview {
	return v.value
}

func (v *NullablePatchJobApplicationInstancePreview) Set(val *PatchJobApplicationInstancePreview) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchJobApplicationInstancePreview) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchJobApplicationInstancePreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchJobApplicationInstancePreview(val *PatchJobApplicationInstancePreview) *NullablePatchJobApplicationInstancePreview {
	return &NullablePatchJobApplicationInstancePreview{value: val, isSet: true}
}

func (v NullablePatchJobApplicationInstancePreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchJobApplicationInstancePreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
