/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CCUStatusAggregateDataContainerTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CCUStatusAggregateDataContainerTelemetry{}

// CCUStatusAggregateDataContainerTelemetry struct for CCUStatusAggregateDataContainerTelemetry
type CCUStatusAggregateDataContainerTelemetry struct {
	// Unix time in which the data was saved
	Timestamp int32 `json:"timestamp"`
	// List containing the telemetry data grouped by providerId
	Ccus []CCUStatusAggregateDataTelemetry `json:"ccus"`
}

type _CCUStatusAggregateDataContainerTelemetry CCUStatusAggregateDataContainerTelemetry

// NewCCUStatusAggregateDataContainerTelemetry instantiates a new CCUStatusAggregateDataContainerTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCCUStatusAggregateDataContainerTelemetry(timestamp int32, ccus []CCUStatusAggregateDataTelemetry) *CCUStatusAggregateDataContainerTelemetry {
	this := CCUStatusAggregateDataContainerTelemetry{}
	this.Timestamp = timestamp
	this.Ccus = ccus
	return &this
}

// NewCCUStatusAggregateDataContainerTelemetryWithDefaults instantiates a new CCUStatusAggregateDataContainerTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCCUStatusAggregateDataContainerTelemetryWithDefaults() *CCUStatusAggregateDataContainerTelemetry {
	this := CCUStatusAggregateDataContainerTelemetry{}
	return &this
}

// GetTimestamp returns the Timestamp field value
func (o *CCUStatusAggregateDataContainerTelemetry) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *CCUStatusAggregateDataContainerTelemetry) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *CCUStatusAggregateDataContainerTelemetry) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetCcus returns the Ccus field value
func (o *CCUStatusAggregateDataContainerTelemetry) GetCcus() []CCUStatusAggregateDataTelemetry {
	if o == nil {
		var ret []CCUStatusAggregateDataTelemetry
		return ret
	}

	return o.Ccus
}

// GetCcusOk returns a tuple with the Ccus field value
// and a boolean to check if the value has been set.
func (o *CCUStatusAggregateDataContainerTelemetry) GetCcusOk() ([]CCUStatusAggregateDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ccus, true
}

// SetCcus sets field value
func (o *CCUStatusAggregateDataContainerTelemetry) SetCcus(v []CCUStatusAggregateDataTelemetry) {
	o.Ccus = v
}

func (o CCUStatusAggregateDataContainerTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CCUStatusAggregateDataContainerTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["ccus"] = o.Ccus
	return toSerialize, nil
}

func (o *CCUStatusAggregateDataContainerTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timestamp",
		"ccus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCCUStatusAggregateDataContainerTelemetry := _CCUStatusAggregateDataContainerTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCCUStatusAggregateDataContainerTelemetry)

	if err != nil {
		return err
	}

	*o = CCUStatusAggregateDataContainerTelemetry(varCCUStatusAggregateDataContainerTelemetry)

	return err
}

type NullableCCUStatusAggregateDataContainerTelemetry struct {
	value *CCUStatusAggregateDataContainerTelemetry
	isSet bool
}

func (v NullableCCUStatusAggregateDataContainerTelemetry) Get() *CCUStatusAggregateDataContainerTelemetry {
	return v.value
}

func (v *NullableCCUStatusAggregateDataContainerTelemetry) Set(val *CCUStatusAggregateDataContainerTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableCCUStatusAggregateDataContainerTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableCCUStatusAggregateDataContainerTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCCUStatusAggregateDataContainerTelemetry(val *CCUStatusAggregateDataContainerTelemetry) *NullableCCUStatusAggregateDataContainerTelemetry {
	return &NullableCCUStatusAggregateDataContainerTelemetry{value: val, isSet: true}
}

func (v NullableCCUStatusAggregateDataContainerTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCCUStatusAggregateDataContainerTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
