/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostCpuTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostCpuTelemetry{}

// HostCpuTelemetry struct for HostCpuTelemetry
type HostCpuTelemetry struct {
	// Unit of data frequency, which is always '1m' in this endpoint
	Unit string `json:"unit"`
	// Contains the data object
	Data []HostCpuDataTelemetry `json:"data"`
}

type _HostCpuTelemetry HostCpuTelemetry

// NewHostCpuTelemetry instantiates a new HostCpuTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostCpuTelemetry(unit string, data []HostCpuDataTelemetry) *HostCpuTelemetry {
	this := HostCpuTelemetry{}
	this.Unit = unit
	this.Data = data
	return &this
}

// NewHostCpuTelemetryWithDefaults instantiates a new HostCpuTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostCpuTelemetryWithDefaults() *HostCpuTelemetry {
	this := HostCpuTelemetry{}
	return &this
}

// GetUnit returns the Unit field value
func (o *HostCpuTelemetry) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *HostCpuTelemetry) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *HostCpuTelemetry) SetUnit(v string) {
	o.Unit = v
}

// GetData returns the Data field value
func (o *HostCpuTelemetry) GetData() []HostCpuDataTelemetry {
	if o == nil {
		var ret []HostCpuDataTelemetry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *HostCpuTelemetry) GetDataOk() ([]HostCpuDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *HostCpuTelemetry) SetData(v []HostCpuDataTelemetry) {
	o.Data = v
}

func (o HostCpuTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostCpuTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unit"] = o.Unit
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *HostCpuTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostCpuTelemetry := _HostCpuTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostCpuTelemetry)

	if err != nil {
		return err
	}

	*o = HostCpuTelemetry(varHostCpuTelemetry)

	return err
}

type NullableHostCpuTelemetry struct {
	value *HostCpuTelemetry
	isSet bool
}

func (v NullableHostCpuTelemetry) Get() *HostCpuTelemetry {
	return v.value
}

func (v *NullableHostCpuTelemetry) Set(val *HostCpuTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableHostCpuTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableHostCpuTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostCpuTelemetry(val *HostCpuTelemetry) *NullableHostCpuTelemetry {
	return &NullableHostCpuTelemetry{value: val, isSet: true}
}

func (v NullableHostCpuTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostCpuTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
