/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CloudCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudCredentials{}

// CloudCredentials struct for CloudCredentials
type CloudCredentials struct {
	// Cloud provider ID. For a list of cloud providers see [`GET /v3/cloud/provider`](#/Cloud/get_v3_cloud_provider)
	ProviderId int32 `json:"providerId"`
	// User defined name for the cloud credential
	Name   string                 `json:"name"`
	Params CloudCredentialsParams `json:"params"`
	// Unix timestamp of when credentials were first stored (informative only)
	CreatedAt int32 `json:"createdAt"`
	// Unix timestamp of credential last verification time (informative only)
	VerifiedAt int32 `json:"verifiedAt"`
	// Status of cloud credential * 0: valid * 1: invalid
	CredentialStatus int32 `json:"credentialStatus"`
	// Unix timestamp of invalidation
	InvalidateAt int32 `json:"invalidateAt"`
	// The reason for invalidation of the cloud credential
	InvalidateReason string `json:"invalidateReason"`
	// Status of a currently in use cloud credential * 0: inactive * 1: active
	Status int32 `json:"status"`
}

type _CloudCredentials CloudCredentials

// NewCloudCredentials instantiates a new CloudCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudCredentials(providerId int32, name string, params CloudCredentialsParams, createdAt int32, verifiedAt int32, credentialStatus int32, invalidateAt int32, invalidateReason string, status int32) *CloudCredentials {
	this := CloudCredentials{}
	this.ProviderId = providerId
	this.Name = name
	this.Params = params
	this.CreatedAt = createdAt
	this.VerifiedAt = verifiedAt
	this.CredentialStatus = credentialStatus
	this.InvalidateAt = invalidateAt
	this.InvalidateReason = invalidateReason
	this.Status = status
	return &this
}

// NewCloudCredentialsWithDefaults instantiates a new CloudCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudCredentialsWithDefaults() *CloudCredentials {
	this := CloudCredentials{}
	return &this
}

// GetProviderId returns the ProviderId field value
func (o *CloudCredentials) GetProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CloudCredentials) SetProviderId(v int32) {
	o.ProviderId = v
}

// GetName returns the Name field value
func (o *CloudCredentials) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudCredentials) SetName(v string) {
	o.Name = v
}

// GetParams returns the Params field value
func (o *CloudCredentials) GetParams() CloudCredentialsParams {
	if o == nil {
		var ret CloudCredentialsParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetParamsOk() (*CloudCredentialsParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *CloudCredentials) SetParams(v CloudCredentialsParams) {
	o.Params = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CloudCredentials) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CloudCredentials) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetVerifiedAt returns the VerifiedAt field value
func (o *CloudCredentials) GetVerifiedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetVerifiedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerifiedAt, true
}

// SetVerifiedAt sets field value
func (o *CloudCredentials) SetVerifiedAt(v int32) {
	o.VerifiedAt = v
}

// GetCredentialStatus returns the CredentialStatus field value
func (o *CloudCredentials) GetCredentialStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CredentialStatus
}

// GetCredentialStatusOk returns a tuple with the CredentialStatus field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetCredentialStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialStatus, true
}

// SetCredentialStatus sets field value
func (o *CloudCredentials) SetCredentialStatus(v int32) {
	o.CredentialStatus = v
}

// GetInvalidateAt returns the InvalidateAt field value
func (o *CloudCredentials) GetInvalidateAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InvalidateAt
}

// GetInvalidateAtOk returns a tuple with the InvalidateAt field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetInvalidateAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidateAt, true
}

// SetInvalidateAt sets field value
func (o *CloudCredentials) SetInvalidateAt(v int32) {
	o.InvalidateAt = v
}

// GetInvalidateReason returns the InvalidateReason field value
func (o *CloudCredentials) GetInvalidateReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvalidateReason
}

// GetInvalidateReasonOk returns a tuple with the InvalidateReason field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetInvalidateReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidateReason, true
}

// SetInvalidateReason sets field value
func (o *CloudCredentials) SetInvalidateReason(v string) {
	o.InvalidateReason = v
}

// GetStatus returns the Status field value
func (o *CloudCredentials) GetStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CloudCredentials) GetStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CloudCredentials) SetStatus(v int32) {
	o.Status = v
}

func (o CloudCredentials) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerId"] = o.ProviderId
	toSerialize["name"] = o.Name
	toSerialize["params"] = o.Params
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["verifiedAt"] = o.VerifiedAt
	toSerialize["credentialStatus"] = o.CredentialStatus
	toSerialize["invalidateAt"] = o.InvalidateAt
	toSerialize["invalidateReason"] = o.InvalidateReason
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *CloudCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"providerId",
		"name",
		"params",
		"createdAt",
		"verifiedAt",
		"credentialStatus",
		"invalidateAt",
		"invalidateReason",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCloudCredentials := _CloudCredentials{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCloudCredentials)

	if err != nil {
		return err
	}

	*o = CloudCredentials(varCloudCredentials)

	return err
}

type NullableCloudCredentials struct {
	value *CloudCredentials
	isSet bool
}

func (v NullableCloudCredentials) Get() *CloudCredentials {
	return v.value
}

func (v *NullableCloudCredentials) Set(val *CloudCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudCredentials(val *CloudCredentials) *NullableCloudCredentials {
	return &NullableCloudCredentials{value: val, isSet: true}
}

func (v NullableCloudCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
