/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostIP{}

// HostIP struct for HostIP
type HostIP struct {
	// Host IP address
	IpAddress string `json:"ipAddress"`
	// IP version, possible values can be 4 or 6
	Version int32 `json:"version"`
	// IP type: 1) normal, 2) KVM, 253) VRRP1, 254) VRRP2, 255) gateway
	Type int32 `json:"type"`
	// Private IP (1) or public IP (0)
	Private int32 `json:"private"`
	// ID of the interface (0-7)
	Interface int32 `json:"interface"`
	// MAC address of the interface
	MacAddress string `json:"macAddress"`
	// RDNS of the interface
	RDns string `json:"rDns"`
	// ID for the VLAN
	VlanId NullableInt32 `json:"vlanId"`
	// Interface gateway
	Gateway NullableString `json:"gateway"`
	// Interface netmask
	Netmask NullableString `json:"netmask"`
	// Interface prefix
	Prefix NullableInt32 `json:"prefix"`
}

type _HostIP HostIP

// NewHostIP instantiates a new HostIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostIP(ipAddress string, version int32, type_ int32, private int32, interface_ int32, macAddress string, rDns string, vlanId NullableInt32, gateway NullableString, netmask NullableString, prefix NullableInt32) *HostIP {
	this := HostIP{}
	this.IpAddress = ipAddress
	this.Version = version
	this.Type = type_
	this.Private = private
	this.Interface = interface_
	this.MacAddress = macAddress
	this.RDns = rDns
	this.VlanId = vlanId
	this.Gateway = gateway
	this.Netmask = netmask
	this.Prefix = prefix
	return &this
}

// NewHostIPWithDefaults instantiates a new HostIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostIPWithDefaults() *HostIP {
	this := HostIP{}
	return &this
}

// GetIpAddress returns the IpAddress field value
func (o *HostIP) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *HostIP) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetVersion returns the Version field value
func (o *HostIP) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HostIP) SetVersion(v int32) {
	o.Version = v
}

// GetType returns the Type field value
func (o *HostIP) GetType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HostIP) SetType(v int32) {
	o.Type = v
}

// GetPrivate returns the Private field value
func (o *HostIP) GetPrivate() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Private
}

// GetPrivateOk returns a tuple with the Private field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetPrivateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Private, true
}

// SetPrivate sets field value
func (o *HostIP) SetPrivate(v int32) {
	o.Private = v
}

// GetInterface returns the Interface field value
func (o *HostIP) GetInterface() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetInterfaceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Interface, true
}

// SetInterface sets field value
func (o *HostIP) SetInterface(v int32) {
	o.Interface = v
}

// GetMacAddress returns the MacAddress field value
func (o *HostIP) GetMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MacAddress, true
}

// SetMacAddress sets field value
func (o *HostIP) SetMacAddress(v string) {
	o.MacAddress = v
}

// GetRDns returns the RDns field value
func (o *HostIP) GetRDns() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RDns
}

// GetRDnsOk returns a tuple with the RDns field value
// and a boolean to check if the value has been set.
func (o *HostIP) GetRDnsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RDns, true
}

// SetRDns sets field value
func (o *HostIP) SetRDns(v string) {
	o.RDns = v
}

// GetVlanId returns the VlanId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *HostIP) GetVlanId() int32 {
	if o == nil || o.VlanId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.VlanId.Get()
}

// GetVlanIdOk returns a tuple with the VlanId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HostIP) GetVlanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VlanId.Get(), o.VlanId.IsSet()
}

// SetVlanId sets field value
func (o *HostIP) SetVlanId(v int32) {
	o.VlanId.Set(&v)
}

// GetGateway returns the Gateway field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HostIP) GetGateway() string {
	if o == nil || o.Gateway.Get() == nil {
		var ret string
		return ret
	}

	return *o.Gateway.Get()
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HostIP) GetGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gateway.Get(), o.Gateway.IsSet()
}

// SetGateway sets field value
func (o *HostIP) SetGateway(v string) {
	o.Gateway.Set(&v)
}

// GetNetmask returns the Netmask field value
// If the value is explicit nil, the zero value for string will be returned
func (o *HostIP) GetNetmask() string {
	if o == nil || o.Netmask.Get() == nil {
		var ret string
		return ret
	}

	return *o.Netmask.Get()
}

// GetNetmaskOk returns a tuple with the Netmask field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HostIP) GetNetmaskOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Netmask.Get(), o.Netmask.IsSet()
}

// SetNetmask sets field value
func (o *HostIP) SetNetmask(v string) {
	o.Netmask.Set(&v)
}

// GetPrefix returns the Prefix field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *HostIP) GetPrefix() int32 {
	if o == nil || o.Prefix.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Prefix.Get()
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HostIP) GetPrefixOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefix.Get(), o.Prefix.IsSet()
}

// SetPrefix sets field value
func (o *HostIP) SetPrefix(v int32) {
	o.Prefix.Set(&v)
}

func (o HostIP) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ipAddress"] = o.IpAddress
	toSerialize["version"] = o.Version
	toSerialize["type"] = o.Type
	toSerialize["private"] = o.Private
	toSerialize["interface"] = o.Interface
	toSerialize["macAddress"] = o.MacAddress
	toSerialize["rDns"] = o.RDns
	toSerialize["vlanId"] = o.VlanId.Get()
	toSerialize["gateway"] = o.Gateway.Get()
	toSerialize["netmask"] = o.Netmask.Get()
	toSerialize["prefix"] = o.Prefix.Get()
	return toSerialize, nil
}

func (o *HostIP) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ipAddress",
		"version",
		"type",
		"private",
		"interface",
		"macAddress",
		"rDns",
		"vlanId",
		"gateway",
		"netmask",
		"prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostIP := _HostIP{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostIP)

	if err != nil {
		return err
	}

	*o = HostIP(varHostIP)

	return err
}

type NullableHostIP struct {
	value *HostIP
	isSet bool
}

func (v NullableHostIP) Get() *HostIP {
	return v.value
}

func (v *NullableHostIP) Set(val *HostIP) {
	v.value = val
	v.isSet = true
}

func (v NullableHostIP) IsSet() bool {
	return v.isSet
}

func (v *NullableHostIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostIP(val *HostIP) *NullableHostIP {
	return &NullableHostIP{value: val, isSet: true}
}

func (v NullableHostIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
