/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceStatus{}

// ApplicationInstanceStatus struct for ApplicationInstanceStatus
type ApplicationInstanceStatus struct {
	// Status code of an application instance
	StatusId int32 `json:"statusId"`
	// Application instance status name
	StatusDescription string `json:"statusDescription"`
	// Application instance status description
	Description string `json:"description"`
	// If isDependency=1, status code represent for application instance dependency installer and uninstaller, in case of isDependency=0 status code represents application instance game and utility type
	IsDependency int32 `json:"isDependency"`
}

type _ApplicationInstanceStatus ApplicationInstanceStatus

// NewApplicationInstanceStatus instantiates a new ApplicationInstanceStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceStatus(statusId int32, statusDescription string, description string, isDependency int32) *ApplicationInstanceStatus {
	this := ApplicationInstanceStatus{}
	this.StatusId = statusId
	this.StatusDescription = statusDescription
	this.Description = description
	this.IsDependency = isDependency
	return &this
}

// NewApplicationInstanceStatusWithDefaults instantiates a new ApplicationInstanceStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceStatusWithDefaults() *ApplicationInstanceStatus {
	this := ApplicationInstanceStatus{}
	return &this
}

// GetStatusId returns the StatusId field value
func (o *ApplicationInstanceStatus) GetStatusId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StatusId
}

// GetStatusIdOk returns a tuple with the StatusId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStatus) GetStatusIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusId, true
}

// SetStatusId sets field value
func (o *ApplicationInstanceStatus) SetStatusId(v int32) {
	o.StatusId = v
}

// GetStatusDescription returns the StatusDescription field value
func (o *ApplicationInstanceStatus) GetStatusDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StatusDescription
}

// GetStatusDescriptionOk returns a tuple with the StatusDescription field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStatus) GetStatusDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusDescription, true
}

// SetStatusDescription sets field value
func (o *ApplicationInstanceStatus) SetStatusDescription(v string) {
	o.StatusDescription = v
}

// GetDescription returns the Description field value
func (o *ApplicationInstanceStatus) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStatus) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ApplicationInstanceStatus) SetDescription(v string) {
	o.Description = v
}

// GetIsDependency returns the IsDependency field value
func (o *ApplicationInstanceStatus) GetIsDependency() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IsDependency
}

// GetIsDependencyOk returns a tuple with the IsDependency field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceStatus) GetIsDependencyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDependency, true
}

// SetIsDependency sets field value
func (o *ApplicationInstanceStatus) SetIsDependency(v int32) {
	o.IsDependency = v
}

func (o ApplicationInstanceStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statusId"] = o.StatusId
	toSerialize["statusDescription"] = o.StatusDescription
	toSerialize["description"] = o.Description
	toSerialize["isDependency"] = o.IsDependency
	return toSerialize, nil
}

func (o *ApplicationInstanceStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statusId",
		"statusDescription",
		"description",
		"isDependency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceStatus := _ApplicationInstanceStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceStatus)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceStatus(varApplicationInstanceStatus)

	return err
}

type NullableApplicationInstanceStatus struct {
	value *ApplicationInstanceStatus
	isSet bool
}

func (v NullableApplicationInstanceStatus) Get() *ApplicationInstanceStatus {
	return v.value
}

func (v *NullableApplicationInstanceStatus) Set(val *ApplicationInstanceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceStatus(val *ApplicationInstanceStatus) *NullableApplicationInstanceStatus {
	return &NullableApplicationInstanceStatus{value: val, isSet: true}
}

func (v NullableApplicationInstanceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
