/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BuildProvisioningFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildProvisioningFile{}

// BuildProvisioningFile struct for BuildProvisioningFile
type BuildProvisioningFile struct {
	// Build provisioning file ID
	Id string `json:"id"`
	// ID of the build provisioning storage registration
	BuildProvisionRegistrationId string `json:"buildProvisionRegistrationId"`
	// Name of the file
	FileName string `json:"fileName"`
	// Size of the file
	FileSize int32 `json:"fileSize"`
	// MD5 checksum of the file
	Md5CheckSum string `json:"md5CheckSum"`
	// UNIX timestamp when the file has been created
	CreatedAt int32 `json:"createdAt"`
	// UNIX timestamp when the file last has been changed
	ChangedAt int32 `json:"changedAt"`
}

type _BuildProvisioningFile BuildProvisioningFile

// NewBuildProvisioningFile instantiates a new BuildProvisioningFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildProvisioningFile(id string, buildProvisionRegistrationId string, fileName string, fileSize int32, md5CheckSum string, createdAt int32, changedAt int32) *BuildProvisioningFile {
	this := BuildProvisioningFile{}
	this.Id = id
	this.BuildProvisionRegistrationId = buildProvisionRegistrationId
	this.FileName = fileName
	this.FileSize = fileSize
	this.Md5CheckSum = md5CheckSum
	this.CreatedAt = createdAt
	this.ChangedAt = changedAt
	return &this
}

// NewBuildProvisioningFileWithDefaults instantiates a new BuildProvisioningFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildProvisioningFileWithDefaults() *BuildProvisioningFile {
	this := BuildProvisioningFile{}
	return &this
}

// GetId returns the Id field value
func (o *BuildProvisioningFile) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BuildProvisioningFile) SetId(v string) {
	o.Id = v
}

// GetBuildProvisionRegistrationId returns the BuildProvisionRegistrationId field value
func (o *BuildProvisioningFile) GetBuildProvisionRegistrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BuildProvisionRegistrationId
}

// GetBuildProvisionRegistrationIdOk returns a tuple with the BuildProvisionRegistrationId field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetBuildProvisionRegistrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BuildProvisionRegistrationId, true
}

// SetBuildProvisionRegistrationId sets field value
func (o *BuildProvisioningFile) SetBuildProvisionRegistrationId(v string) {
	o.BuildProvisionRegistrationId = v
}

// GetFileName returns the FileName field value
func (o *BuildProvisioningFile) GetFileName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetFileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileName, true
}

// SetFileName sets field value
func (o *BuildProvisioningFile) SetFileName(v string) {
	o.FileName = v
}

// GetFileSize returns the FileSize field value
func (o *BuildProvisioningFile) GetFileSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetFileSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileSize, true
}

// SetFileSize sets field value
func (o *BuildProvisioningFile) SetFileSize(v int32) {
	o.FileSize = v
}

// GetMd5CheckSum returns the Md5CheckSum field value
func (o *BuildProvisioningFile) GetMd5CheckSum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Md5CheckSum
}

// GetMd5CheckSumOk returns a tuple with the Md5CheckSum field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetMd5CheckSumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Md5CheckSum, true
}

// SetMd5CheckSum sets field value
func (o *BuildProvisioningFile) SetMd5CheckSum(v string) {
	o.Md5CheckSum = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BuildProvisioningFile) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BuildProvisioningFile) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetChangedAt returns the ChangedAt field value
func (o *BuildProvisioningFile) GetChangedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChangedAt
}

// GetChangedAtOk returns a tuple with the ChangedAt field value
// and a boolean to check if the value has been set.
func (o *BuildProvisioningFile) GetChangedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangedAt, true
}

// SetChangedAt sets field value
func (o *BuildProvisioningFile) SetChangedAt(v int32) {
	o.ChangedAt = v
}

func (o BuildProvisioningFile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildProvisioningFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["buildProvisionRegistrationId"] = o.BuildProvisionRegistrationId
	toSerialize["fileName"] = o.FileName
	toSerialize["fileSize"] = o.FileSize
	toSerialize["md5CheckSum"] = o.Md5CheckSum
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["changedAt"] = o.ChangedAt
	return toSerialize, nil
}

func (o *BuildProvisioningFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"buildProvisionRegistrationId",
		"fileName",
		"fileSize",
		"md5CheckSum",
		"createdAt",
		"changedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildProvisioningFile := _BuildProvisioningFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildProvisioningFile)

	if err != nil {
		return err
	}

	*o = BuildProvisioningFile(varBuildProvisioningFile)

	return err
}

type NullableBuildProvisioningFile struct {
	value *BuildProvisioningFile
	isSet bool
}

func (v NullableBuildProvisioningFile) Get() *BuildProvisioningFile {
	return v.value
}

func (v *NullableBuildProvisioningFile) Set(val *BuildProvisioningFile) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildProvisioningFile) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildProvisioningFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildProvisioningFile(val *BuildProvisioningFile) *NullableBuildProvisioningFile {
	return &NullableBuildProvisioningFile{value: val, isSet: true}
}

func (v NullableBuildProvisioningFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildProvisioningFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
