/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationProperty{}

// ApplicationProperty struct for ApplicationProperty
type ApplicationProperty struct {
	// The application property ID
	Id string `json:"id"`
	// The application property type. For a list of application property types see [`GET /v3/application/property/type`](#/Application/get_v3_application_property_type)
	PropertyType int32 `json:"propertyType"`
	// The application property key. Only hyphens (-), underscores (_), lowercase characters and numbers are allowed. Keys must start with a lowercase character
	PropertyKey string `json:"propertyKey"`
	// The application property value
	PropertyValue *string `json:"propertyValue,omitempty"`
}

type _ApplicationProperty ApplicationProperty

// NewApplicationProperty instantiates a new ApplicationProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationProperty(id string, propertyType int32, propertyKey string) *ApplicationProperty {
	this := ApplicationProperty{}
	this.Id = id
	this.PropertyType = propertyType
	this.PropertyKey = propertyKey
	return &this
}

// NewApplicationPropertyWithDefaults instantiates a new ApplicationProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationPropertyWithDefaults() *ApplicationProperty {
	this := ApplicationProperty{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationProperty) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationProperty) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationProperty) SetId(v string) {
	o.Id = v
}

// GetPropertyType returns the PropertyType field value
func (o *ApplicationProperty) GetPropertyType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PropertyType
}

// GetPropertyTypeOk returns a tuple with the PropertyType field value
// and a boolean to check if the value has been set.
func (o *ApplicationProperty) GetPropertyTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyType, true
}

// SetPropertyType sets field value
func (o *ApplicationProperty) SetPropertyType(v int32) {
	o.PropertyType = v
}

// GetPropertyKey returns the PropertyKey field value
func (o *ApplicationProperty) GetPropertyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyKey
}

// GetPropertyKeyOk returns a tuple with the PropertyKey field value
// and a boolean to check if the value has been set.
func (o *ApplicationProperty) GetPropertyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PropertyKey, true
}

// SetPropertyKey sets field value
func (o *ApplicationProperty) SetPropertyKey(v string) {
	o.PropertyKey = v
}

// GetPropertyValue returns the PropertyValue field value if set, zero value otherwise.
func (o *ApplicationProperty) GetPropertyValue() string {
	if o == nil || IsNil(o.PropertyValue) {
		var ret string
		return ret
	}
	return *o.PropertyValue
}

// GetPropertyValueOk returns a tuple with the PropertyValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationProperty) GetPropertyValueOk() (*string, bool) {
	if o == nil || IsNil(o.PropertyValue) {
		return nil, false
	}
	return o.PropertyValue, true
}

// HasPropertyValue returns a boolean if a field has been set.
func (o *ApplicationProperty) HasPropertyValue() bool {
	if o != nil && !IsNil(o.PropertyValue) {
		return true
	}

	return false
}

// SetPropertyValue gets a reference to the given string and assigns it to the PropertyValue field.
func (o *ApplicationProperty) SetPropertyValue(v string) {
	o.PropertyValue = &v
}

func (o ApplicationProperty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["propertyType"] = o.PropertyType
	toSerialize["propertyKey"] = o.PropertyKey
	if !IsNil(o.PropertyValue) {
		toSerialize["propertyValue"] = o.PropertyValue
	}
	return toSerialize, nil
}

func (o *ApplicationProperty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"propertyType",
		"propertyKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationProperty := _ApplicationProperty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationProperty)

	if err != nil {
		return err
	}

	*o = ApplicationProperty(varApplicationProperty)

	return err
}

type NullableApplicationProperty struct {
	value *ApplicationProperty
	isSet bool
}

func (v NullableApplicationProperty) Get() *ApplicationProperty {
	return v.value
}

func (v *NullableApplicationProperty) Set(val *ApplicationProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationProperty(val *ApplicationProperty) *NullableApplicationProperty {
	return &NullableApplicationProperty{value: val, isSet: true}
}

func (v NullableApplicationProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
