/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceByRegion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceByRegion{}

// ApplicationInstanceByRegion struct for ApplicationInstanceByRegion
type ApplicationInstanceByRegion struct {
	// The ID of the deployment region
	RegionId string `json:"regionId"`
	// Amount of allocatable instances for the deployment region
	AllocatableInstances int32 `json:"allocatableInstances"`
	// List of application instances ID's
	ApplicationInstances []string `json:"applicationInstances"`
}

type _ApplicationInstanceByRegion ApplicationInstanceByRegion

// NewApplicationInstanceByRegion instantiates a new ApplicationInstanceByRegion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceByRegion(regionId string, allocatableInstances int32, applicationInstances []string) *ApplicationInstanceByRegion {
	this := ApplicationInstanceByRegion{}
	this.RegionId = regionId
	this.AllocatableInstances = allocatableInstances
	this.ApplicationInstances = applicationInstances
	return &this
}

// NewApplicationInstanceByRegionWithDefaults instantiates a new ApplicationInstanceByRegion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceByRegionWithDefaults() *ApplicationInstanceByRegion {
	this := ApplicationInstanceByRegion{}
	return &this
}

// GetRegionId returns the RegionId field value
func (o *ApplicationInstanceByRegion) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceByRegion) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *ApplicationInstanceByRegion) SetRegionId(v string) {
	o.RegionId = v
}

// GetAllocatableInstances returns the AllocatableInstances field value
func (o *ApplicationInstanceByRegion) GetAllocatableInstances() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AllocatableInstances
}

// GetAllocatableInstancesOk returns a tuple with the AllocatableInstances field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceByRegion) GetAllocatableInstancesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllocatableInstances, true
}

// SetAllocatableInstances sets field value
func (o *ApplicationInstanceByRegion) SetAllocatableInstances(v int32) {
	o.AllocatableInstances = v
}

// GetApplicationInstances returns the ApplicationInstances field value
func (o *ApplicationInstanceByRegion) GetApplicationInstances() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ApplicationInstances
}

// GetApplicationInstancesOk returns a tuple with the ApplicationInstances field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceByRegion) GetApplicationInstancesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApplicationInstances, true
}

// SetApplicationInstances sets field value
func (o *ApplicationInstanceByRegion) SetApplicationInstances(v []string) {
	o.ApplicationInstances = v
}

func (o ApplicationInstanceByRegion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceByRegion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionId"] = o.RegionId
	toSerialize["allocatableInstances"] = o.AllocatableInstances
	toSerialize["applicationInstances"] = o.ApplicationInstances
	return toSerialize, nil
}

func (o *ApplicationInstanceByRegion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionId",
		"allocatableInstances",
		"applicationInstances",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceByRegion := _ApplicationInstanceByRegion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceByRegion)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceByRegion(varApplicationInstanceByRegion)

	return err
}

type NullableApplicationInstanceByRegion struct {
	value *ApplicationInstanceByRegion
	isSet bool
}

func (v NullableApplicationInstanceByRegion) Get() *ApplicationInstanceByRegion {
	return v.value
}

func (v *NullableApplicationInstanceByRegion) Set(val *ApplicationInstanceByRegion) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceByRegion) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceByRegion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceByRegion(val *ApplicationInstanceByRegion) *NullableApplicationInstanceByRegion {
	return &NullableApplicationInstanceByRegion{value: val, isSet: true}
}

func (v NullableApplicationInstanceByRegion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceByRegion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
