/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the HostOveruseTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostOveruseTelemetry{}

// HostOveruseTelemetry struct for HostOveruseTelemetry
type HostOveruseTelemetry struct {
	// The ID of the host
	HostId int32 `json:"hostId"`
	// The name of the physical machine
	HostName string `json:"hostName"`
	// Allowed bandwidth of the host
	OrderedBandwidth float32 `json:"orderedBandwidth"`
	// Used bandwidth of the host
	UsedBandwidth float32 `json:"usedBandwidth"`
}

type _HostOveruseTelemetry HostOveruseTelemetry

// NewHostOveruseTelemetry instantiates a new HostOveruseTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostOveruseTelemetry(hostId int32, hostName string, orderedBandwidth float32, usedBandwidth float32) *HostOveruseTelemetry {
	this := HostOveruseTelemetry{}
	this.HostId = hostId
	this.HostName = hostName
	this.OrderedBandwidth = orderedBandwidth
	this.UsedBandwidth = usedBandwidth
	return &this
}

// NewHostOveruseTelemetryWithDefaults instantiates a new HostOveruseTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostOveruseTelemetryWithDefaults() *HostOveruseTelemetry {
	this := HostOveruseTelemetry{}
	return &this
}

// GetHostId returns the HostId field value
func (o *HostOveruseTelemetry) GetHostId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value
// and a boolean to check if the value has been set.
func (o *HostOveruseTelemetry) GetHostIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostId, true
}

// SetHostId sets field value
func (o *HostOveruseTelemetry) SetHostId(v int32) {
	o.HostId = v
}

// GetHostName returns the HostName field value
func (o *HostOveruseTelemetry) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *HostOveruseTelemetry) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *HostOveruseTelemetry) SetHostName(v string) {
	o.HostName = v
}

// GetOrderedBandwidth returns the OrderedBandwidth field value
func (o *HostOveruseTelemetry) GetOrderedBandwidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OrderedBandwidth
}

// GetOrderedBandwidthOk returns a tuple with the OrderedBandwidth field value
// and a boolean to check if the value has been set.
func (o *HostOveruseTelemetry) GetOrderedBandwidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderedBandwidth, true
}

// SetOrderedBandwidth sets field value
func (o *HostOveruseTelemetry) SetOrderedBandwidth(v float32) {
	o.OrderedBandwidth = v
}

// GetUsedBandwidth returns the UsedBandwidth field value
func (o *HostOveruseTelemetry) GetUsedBandwidth() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.UsedBandwidth
}

// GetUsedBandwidthOk returns a tuple with the UsedBandwidth field value
// and a boolean to check if the value has been set.
func (o *HostOveruseTelemetry) GetUsedBandwidthOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedBandwidth, true
}

// SetUsedBandwidth sets field value
func (o *HostOveruseTelemetry) SetUsedBandwidth(v float32) {
	o.UsedBandwidth = v
}

func (o HostOveruseTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostOveruseTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostId"] = o.HostId
	toSerialize["hostName"] = o.HostName
	toSerialize["orderedBandwidth"] = o.OrderedBandwidth
	toSerialize["usedBandwidth"] = o.UsedBandwidth
	return toSerialize, nil
}

func (o *HostOveruseTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostId",
		"hostName",
		"orderedBandwidth",
		"usedBandwidth",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostOveruseTelemetry := _HostOveruseTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostOveruseTelemetry)

	if err != nil {
		return err
	}

	*o = HostOveruseTelemetry(varHostOveruseTelemetry)

	return err
}

type NullableHostOveruseTelemetry struct {
	value *HostOveruseTelemetry
	isSet bool
}

func (v NullableHostOveruseTelemetry) Get() *HostOveruseTelemetry {
	return v.value
}

func (v *NullableHostOveruseTelemetry) Set(val *HostOveruseTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableHostOveruseTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableHostOveruseTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostOveruseTelemetry(val *HostOveruseTelemetry) *NullableHostOveruseTelemetry {
	return &NullableHostOveruseTelemetry{value: val, isSet: true}
}

func (v NullableHostOveruseTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostOveruseTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
