/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceMemoryTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceMemoryTelemetry{}

// ApplicationInstanceMemoryTelemetry struct for ApplicationInstanceMemoryTelemetry
type ApplicationInstanceMemoryTelemetry struct {
	// Unit of data frequency, which is always `null` in this endpoint. This property is there for consistency across all telemetry endpoints. It's `null` because the data is not aggregated
	Unit string `json:"unit"`
	// Contains the data object
	Data []ApplicationInstanceMemoryDataTelemetry `json:"data"`
}

type _ApplicationInstanceMemoryTelemetry ApplicationInstanceMemoryTelemetry

// NewApplicationInstanceMemoryTelemetry instantiates a new ApplicationInstanceMemoryTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceMemoryTelemetry(unit string, data []ApplicationInstanceMemoryDataTelemetry) *ApplicationInstanceMemoryTelemetry {
	this := ApplicationInstanceMemoryTelemetry{}
	this.Unit = unit
	this.Data = data
	return &this
}

// NewApplicationInstanceMemoryTelemetryWithDefaults instantiates a new ApplicationInstanceMemoryTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceMemoryTelemetryWithDefaults() *ApplicationInstanceMemoryTelemetry {
	this := ApplicationInstanceMemoryTelemetry{}
	return &this
}

// GetUnit returns the Unit field value
func (o *ApplicationInstanceMemoryTelemetry) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMemoryTelemetry) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *ApplicationInstanceMemoryTelemetry) SetUnit(v string) {
	o.Unit = v
}

// GetData returns the Data field value
func (o *ApplicationInstanceMemoryTelemetry) GetData() []ApplicationInstanceMemoryDataTelemetry {
	if o == nil {
		var ret []ApplicationInstanceMemoryDataTelemetry
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMemoryTelemetry) GetDataOk() ([]ApplicationInstanceMemoryDataTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ApplicationInstanceMemoryTelemetry) SetData(v []ApplicationInstanceMemoryDataTelemetry) {
	o.Data = v
}

func (o ApplicationInstanceMemoryTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceMemoryTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unit"] = o.Unit
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApplicationInstanceMemoryTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceMemoryTelemetry := _ApplicationInstanceMemoryTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceMemoryTelemetry)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceMemoryTelemetry(varApplicationInstanceMemoryTelemetry)

	return err
}

type NullableApplicationInstanceMemoryTelemetry struct {
	value *ApplicationInstanceMemoryTelemetry
	isSet bool
}

func (v NullableApplicationInstanceMemoryTelemetry) Get() *ApplicationInstanceMemoryTelemetry {
	return v.value
}

func (v *NullableApplicationInstanceMemoryTelemetry) Set(val *ApplicationInstanceMemoryTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceMemoryTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceMemoryTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceMemoryTelemetry(val *ApplicationInstanceMemoryTelemetry) *NullableApplicationInstanceMemoryTelemetry {
	return &NullableApplicationInstanceMemoryTelemetry{value: val, isSet: true}
}

func (v NullableApplicationInstanceMemoryTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceMemoryTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
