/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UCSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UCSetting{}

// UCSetting struct for UCSetting
type UCSetting struct {
	// Ubisoft Cloud network setting id
	Id string `json:"id"`
	// Ubisoft Cloud project id
	ProjectId string `json:"projectId"`
	// Ubisoft Cloud region name
	RegionName string `json:"regionName"`
	// Ubisoft Cloud public network UUID id e.g: (b091a99e-abdd-11ea-bb37-0242ac130002)
	PublicNetworkId string `json:"publicNetworkId"`
	// Ubisoft Cloud private network UUID id e.g: (d80e2d7e-aa38-490e-915c-bb56222911c3)
	PrivateNetworkId string `json:"privateNetworkId"`
	// Ubisoft Cloud security group id e.g: (0ec61726-405c-4919-b9a1-9dcd6ae56077)
	SecurityGroupId string `json:"securityGroupId"`
	// UnixTimestamp
	CreatedAt int32 `json:"createdAt"`
	// UnixTimestamp
	ChangedAt int32 `json:"changedAt"`
}

type _UCSetting UCSetting

// NewUCSetting instantiates a new UCSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUCSetting(id string, projectId string, regionName string, publicNetworkId string, privateNetworkId string, securityGroupId string, createdAt int32, changedAt int32) *UCSetting {
	this := UCSetting{}
	this.Id = id
	this.ProjectId = projectId
	this.RegionName = regionName
	this.PublicNetworkId = publicNetworkId
	this.PrivateNetworkId = privateNetworkId
	this.SecurityGroupId = securityGroupId
	this.CreatedAt = createdAt
	this.ChangedAt = changedAt
	return &this
}

// NewUCSettingWithDefaults instantiates a new UCSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUCSettingWithDefaults() *UCSetting {
	this := UCSetting{}
	return &this
}

// GetId returns the Id field value
func (o *UCSetting) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UCSetting) SetId(v string) {
	o.Id = v
}

// GetProjectId returns the ProjectId field value
func (o *UCSetting) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *UCSetting) SetProjectId(v string) {
	o.ProjectId = v
}

// GetRegionName returns the RegionName field value
func (o *UCSetting) GetRegionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionName
}

// GetRegionNameOk returns a tuple with the RegionName field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetRegionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionName, true
}

// SetRegionName sets field value
func (o *UCSetting) SetRegionName(v string) {
	o.RegionName = v
}

// GetPublicNetworkId returns the PublicNetworkId field value
func (o *UCSetting) GetPublicNetworkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicNetworkId
}

// GetPublicNetworkIdOk returns a tuple with the PublicNetworkId field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetPublicNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicNetworkId, true
}

// SetPublicNetworkId sets field value
func (o *UCSetting) SetPublicNetworkId(v string) {
	o.PublicNetworkId = v
}

// GetPrivateNetworkId returns the PrivateNetworkId field value
func (o *UCSetting) GetPrivateNetworkId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrivateNetworkId
}

// GetPrivateNetworkIdOk returns a tuple with the PrivateNetworkId field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetPrivateNetworkIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrivateNetworkId, true
}

// SetPrivateNetworkId sets field value
func (o *UCSetting) SetPrivateNetworkId(v string) {
	o.PrivateNetworkId = v
}

// GetSecurityGroupId returns the SecurityGroupId field value
func (o *UCSetting) GetSecurityGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecurityGroupId
}

// GetSecurityGroupIdOk returns a tuple with the SecurityGroupId field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetSecurityGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecurityGroupId, true
}

// SetSecurityGroupId sets field value
func (o *UCSetting) SetSecurityGroupId(v string) {
	o.SecurityGroupId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UCSetting) GetCreatedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetCreatedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UCSetting) SetCreatedAt(v int32) {
	o.CreatedAt = v
}

// GetChangedAt returns the ChangedAt field value
func (o *UCSetting) GetChangedAt() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChangedAt
}

// GetChangedAtOk returns a tuple with the ChangedAt field value
// and a boolean to check if the value has been set.
func (o *UCSetting) GetChangedAtOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangedAt, true
}

// SetChangedAt sets field value
func (o *UCSetting) SetChangedAt(v int32) {
	o.ChangedAt = v
}

func (o UCSetting) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UCSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["projectId"] = o.ProjectId
	toSerialize["regionName"] = o.RegionName
	toSerialize["publicNetworkId"] = o.PublicNetworkId
	toSerialize["privateNetworkId"] = o.PrivateNetworkId
	toSerialize["securityGroupId"] = o.SecurityGroupId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["changedAt"] = o.ChangedAt
	return toSerialize, nil
}

func (o *UCSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"projectId",
		"regionName",
		"publicNetworkId",
		"privateNetworkId",
		"securityGroupId",
		"createdAt",
		"changedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUCSetting := _UCSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUCSetting)

	if err != nil {
		return err
	}

	*o = UCSetting(varUCSetting)

	return err
}

type NullableUCSetting struct {
	value *UCSetting
	isSet bool
}

func (v NullableUCSetting) Get() *UCSetting {
	return v.value
}

func (v *NullableUCSetting) Set(val *UCSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableUCSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableUCSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUCSetting(val *UCSetting) *NullableUCSetting {
	return &NullableUCSetting{value: val, isSet: true}
}

func (v NullableUCSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUCSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
