/*
i3D.net One-Deployment-Platform Endpoints

Documentation links: - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Usage/\">API Usage</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Authentication/\">API Authentication</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Handling/\">API Error Handling</a> - <a href=\"https://www.i3d.net/docs/one/odp/Platform-Overview/APIv3-Error-Codes/\">API Error Codes</a> - <a href=\"https://www.i3d.net/docs/one/odp/\">All ONE Deployment Platform Documentation</a>

API version: 3.0.0
Contact: info@i3d.net
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry{}

// ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry struct for ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry
type ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry struct {
	// The ID of the deployment profile
	DeploymentProfileId string `json:"deploymentProfileId"`
	// Average number of application instances with setup status
	Setup int32 `json:"setup"`
	// Average number of application instances with offline status
	Offline int32 `json:"offline"`
	// Average number of application instances with starting status
	Starting int32 `json:"starting"`
	// Average number of application instances with online status
	Online int32 `json:"online"`
	// Average number of application instances with allocated status
	Allocated int32 `json:"allocated"`
	// Contains the deployment regions
	DeploymentRegions []ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry `json:"deploymentRegions"`
}

type _ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry

// NewApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry instantiates a new ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry(deploymentProfileId string, setup int32, offline int32, starting int32, online int32, allocated int32, deploymentRegions []ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry) *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry {
	this := ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry{}
	this.DeploymentProfileId = deploymentProfileId
	this.Setup = setup
	this.Offline = offline
	this.Starting = starting
	this.Online = online
	this.Allocated = allocated
	this.DeploymentRegions = deploymentRegions
	return &this
}

// NewApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetryWithDefaults instantiates a new ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetryWithDefaults() *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry {
	this := ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry{}
	return &this
}

// GetDeploymentProfileId returns the DeploymentProfileId field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetDeploymentProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentProfileId
}

// GetDeploymentProfileIdOk returns a tuple with the DeploymentProfileId field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetDeploymentProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentProfileId, true
}

// SetDeploymentProfileId sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetDeploymentProfileId(v string) {
	o.DeploymentProfileId = v
}

// GetSetup returns the Setup field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetSetup() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Setup
}

// GetSetupOk returns a tuple with the Setup field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetSetupOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Setup, true
}

// SetSetup sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetSetup(v int32) {
	o.Setup = v
}

// GetOffline returns the Offline field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetOffline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Offline
}

// GetOfflineOk returns a tuple with the Offline field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetOfflineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offline, true
}

// SetOffline sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetOffline(v int32) {
	o.Offline = v
}

// GetStarting returns the Starting field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetStarting() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Starting
}

// GetStartingOk returns a tuple with the Starting field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetStartingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Starting, true
}

// SetStarting sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetStarting(v int32) {
	o.Starting = v
}

// GetOnline returns the Online field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetOnline() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Online
}

// GetOnlineOk returns a tuple with the Online field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetOnlineOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Online, true
}

// SetOnline sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetOnline(v int32) {
	o.Online = v
}

// GetAllocated returns the Allocated field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetAllocated() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Allocated
}

// GetAllocatedOk returns a tuple with the Allocated field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetAllocatedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Allocated, true
}

// SetAllocated sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetAllocated(v int32) {
	o.Allocated = v
}

// GetDeploymentRegions returns the DeploymentRegions field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetDeploymentRegions() []ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry {
	if o == nil {
		var ret []ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry
		return ret
	}

	return o.DeploymentRegions
}

// GetDeploymentRegionsOk returns a tuple with the DeploymentRegions field value
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) GetDeploymentRegionsOk() ([]ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeploymentRegions, true
}

// SetDeploymentRegions sets field value
func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) SetDeploymentRegions(v []ApplicationInstanceDeploymentProfileStatusDeploymentRegionTelemetry) {
	o.DeploymentRegions = v
}

func (o ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deploymentProfileId"] = o.DeploymentProfileId
	toSerialize["setup"] = o.Setup
	toSerialize["offline"] = o.Offline
	toSerialize["starting"] = o.Starting
	toSerialize["online"] = o.Online
	toSerialize["allocated"] = o.Allocated
	toSerialize["deploymentRegions"] = o.DeploymentRegions
	return toSerialize, nil
}

func (o *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deploymentProfileId",
		"setup",
		"offline",
		"starting",
		"online",
		"allocated",
		"deploymentRegions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry := _ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry)

	if err != nil {
		return err
	}

	*o = ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry(varApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry)

	return err
}

type NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry struct {
	value *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry
	isSet bool
}

func (v NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) Get() *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry {
	return v.value
}

func (v *NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) Set(val *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry(val *ApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) *NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry {
	return &NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry{value: val, isSet: true}
}

func (v NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceDeploymentProfileStatusDeploymentProfileTelemetry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
